// Baza držav za Nakupko: en vir za aplikacijo, iPhone in Android.
// Aplikacija ob zagonu prenese najnovejšo različico (https://myedgeofficial.github.io/nakupko/drzave.js)
// in jo shrani; ta datoteka v aplikaciji je rezerva brez povezave. Pred objavo jo preveri
// native/tests/drzave.test.js (format, jezik, vrste trgovin za tobak, vir cen).
//
// Polja za državo (manjkajoča vzamejo vrednost iz »privzeto«):
//   ime     ime države v njenem jeziku
//   jezik   jezik aplikacije v tej državi (ISO 639-1); če prevoda še ni, angleščina
//   cene    ključ dnevnega vira cen, ki je že vključen (prices-xx.json), ali null = samo trgovine, brez cen
//   vir     opis brezplačnega vira cen (tudi za vire, ki še niso vključeni)
//   tobak   kje se prodajajo cigarete: trafika (specializirana), kiosk (kiosk/časopisi), bencinska, trgovina (supermarket)
//   nedelja »zaprto«, če so trgovine ob nedeljah večinoma zaprte (takrat bencinska za pijačo/prigrizke)
window.NAKUPKO_DRZAVE = {
  "verzija": "2026-10-07",
  "privzeto": { "jezik": "en", "cene": null, "tobak": ["trafika", "kiosk", "bencinska", "trgovina"], "nedelja": "odprto" },
  "drzave": {
    "SI": { "ime": "Slovenija", "jezik": "sl", "cene": "si", "vir": "spletne trgovine verig (vsak dan)", "nedelja": "zaprto" },
    "AT": { "ime": "Österreich", "jezik": "de", "cene": "at", "vir": "heisse-preise.io (Billa, Spar, Hofer, MPreis, dm …; MIT)", "tobak": ["trafika", "bencinska"], "nedelja": "zaprto" },
    "HR": { "ime": "Hrvatska", "jezik": "hr", "cene": "hr", "vir": "zakonsko javni cjeniki vseh verig (NN 75/2025), api.cijene.dev", "nedelja": "zaprto" },
    "HU": { "ime": "Magyarország", "jezik": "hu", "cene": "hu", "vir": "GVH Árfigyelő (državni primerjalnik, dnevna datoteka)", "tobak": ["trafika"] },
    "BG": { "ime": "България", "jezik": "bg", "vir": "kolkostruva.bg/opendata_files (dnevni ZIP vseh večjih verig, brezplačno) – še ni vključeno" },
    "RS": { "ime": "Srbija", "jezik": "sr", "vir": "data.gov.rs (tedenski ceniki 27+ verig, brezplačno) – še ni vključeno" },
    "MK": { "ime": "Северна Македонија", "jezik": "mk", "vir": "trgovci morajo cene vsak dan objaviti na svojih straneh – še ni vključeno" },
    "BA": { "ime": "Bosna i Hercegovina", "jezik": "bs", "vir": "usporedicijene.ba (davčna uprava FBiH) – brez odprtih podatkov" },
    "RO": { "ime": "România", "jezik": "ro", "vir": "Monitorul Prețurilor (Consiliul Concurenței) – brez odprtih podatkov" },
    "GR": { "ime": "Ελλάδα", "jezik": "el", "vir": "PosoKanei (država) – brez odprtih podatkov", "nedelja": "zaprto" },
    "NL": { "ime": "Nederland", "jezik": "nl", "vir": "checkjebon (neuradno, odprta koda) – še ni vključeno", "tobak": ["trafika", "kiosk", "bencinska"] },
    "IT": { "ime": "Italia", "jezik": "it", "tobak": ["trafika"] },
    "FR": { "ime": "France", "jezik": "fr", "tobak": ["trafika"] },
    "ES": { "ime": "España", "jezik": "es", "tobak": ["trafika"] },
    "DE": { "ime": "Deutschland", "jezik": "de", "nedelja": "zaprto" },
    "CH": { "ime": "Schweiz", "jezik": "de", "nedelja": "zaprto" },
    "LI": { "ime": "Liechtenstein", "jezik": "de", "nedelja": "zaprto" },
    "LU": { "ime": "Luxembourg", "jezik": "fr" },
    "BE": { "ime": "België", "jezik": "nl", "tobak": ["trafika", "kiosk", "bencinska"] },
    "PL": { "ime": "Polska", "jezik": "pl", "nedelja": "zaprto" },
    "CZ": { "ime": "Česko", "jezik": "cs" },
    "SK": { "ime": "Slovensko", "jezik": "sk" },
    "ME": { "ime": "Crna Gora", "jezik": "sr" },
    "XK": { "ime": "Kosovë", "jezik": "sq" },
    "AL": { "ime": "Shqipëri", "jezik": "sq" },
    "PT": { "ime": "Portugal", "jezik": "pt" },
    "IE": { "ime": "Ireland", "jezik": "en" },
    "GB": { "ime": "United Kingdom", "jezik": "en" },
    "MT": { "ime": "Malta", "jezik": "en" },
    "CY": { "ime": "Κύπρος", "jezik": "el" },
    "DK": { "ime": "Danmark", "jezik": "da" },
    "SE": { "ime": "Sverige", "jezik": "sv" },
    "NO": { "ime": "Norge", "jezik": "no", "nedelja": "zaprto" },
    "FI": { "ime": "Suomi", "jezik": "fi" },
    "IS": { "ime": "Ísland", "jezik": "is" },
    "EE": { "ime": "Eesti", "jezik": "et" },
    "LV": { "ime": "Latvija", "jezik": "lv" },
    "LT": { "ime": "Lietuva", "jezik": "lt" },
    "UA": { "ime": "Україна", "jezik": "uk" },
    "MD": { "ime": "Moldova", "jezik": "ro" },
    "BY": { "ime": "Беларусь", "jezik": "ru" },
    "RU": { "ime": "Россия", "jezik": "ru" },
    "TR": { "ime": "Türkiye", "jezik": "tr" },
    "GE": { "ime": "საქართველო", "jezik": "ka" },
    "AM": { "ime": "Հայաստան", "jezik": "hy" },
    "AZ": { "ime": "Azərbaycan", "jezik": "az" },
    "KZ": { "ime": "Қазақстан", "jezik": "ru" },
    "KG": { "ime": "Кыргызстан", "jezik": "ru" },
    "TJ": { "ime": "Тоҷикистон", "jezik": "ru" },
    "TM": { "ime": "Türkmenistan", "jezik": "ru" },
    "UZ": { "ime": "Oʻzbekiston", "jezik": "uz" },
    "MN": { "ime": "Монгол", "jezik": "mn" },
    "US": { "ime": "United States", "jezik": "en" },
    "CA": { "ime": "Canada", "jezik": "en" },
    "MX": { "ime": "México", "jezik": "es" },
    "GT": { "ime": "Guatemala", "jezik": "es" },
    "HN": { "ime": "Honduras", "jezik": "es" },
    "SV": { "ime": "El Salvador", "jezik": "es" },
    "NI": { "ime": "Nicaragua", "jezik": "es" },
    "CR": { "ime": "Costa Rica", "jezik": "es" },
    "PA": { "ime": "Panamá", "jezik": "es" },
    "DO": { "ime": "República Dominicana", "jezik": "es" },
    "CO": { "ime": "Colombia", "jezik": "es" },
    "VE": { "ime": "Venezuela", "jezik": "es" },
    "EC": { "ime": "Ecuador", "jezik": "es" },
    "PE": { "ime": "Perú", "jezik": "es" },
    "BO": { "ime": "Bolivia", "jezik": "es" },
    "CL": { "ime": "Chile", "jezik": "es" },
    "AR": { "ime": "Argentina", "jezik": "es" },
    "UY": { "ime": "Uruguay", "jezik": "es" },
    "PY": { "ime": "Paraguay", "jezik": "es" },
    "BR": { "ime": "Brasil", "jezik": "pt" },
    "SR": { "ime": "Suriname", "jezik": "nl" },
    "GY": { "ime": "Guyana", "jezik": "en" },
    "BZ": { "ime": "Belize", "jezik": "en" },
    "JM": { "ime": "Jamaica", "jezik": "en" },
    "TT": { "ime": "Trinidad and Tobago", "jezik": "en" },
    "BB": { "ime": "Barbados", "jezik": "en" },
    "BS": { "ime": "Bahamas", "jezik": "en" },
    "AG": { "ime": "Antigua and Barbuda", "jezik": "en" },
    "DM": { "ime": "Dominica", "jezik": "en" },
    "GD": { "ime": "Grenada", "jezik": "en" },
    "KN": { "ime": "Saint Kitts and Nevis", "jezik": "en" },
    "LC": { "ime": "Saint Lucia", "jezik": "en" },
    "VC": { "ime": "Saint Vincent and the Grenadines", "jezik": "en" },
    "AI": { "ime": "Anguilla", "jezik": "en" },
    "BM": { "ime": "Bermuda", "jezik": "en" },
    "KY": { "ime": "Cayman Islands", "jezik": "en" },
    "MS": { "ime": "Montserrat", "jezik": "en" },
    "TC": { "ime": "Turks and Caicos Islands", "jezik": "en" },
    "VG": { "ime": "British Virgin Islands", "jezik": "en" },
    "AU": { "ime": "Australia", "jezik": "en" },
    "NZ": { "ime": "New Zealand", "jezik": "en" },
    "FJ": { "ime": "Fiji", "jezik": "en" },
    "PG": { "ime": "Papua New Guinea", "jezik": "en" },
    "SB": { "ime": "Solomon Islands", "jezik": "en" },
    "VU": { "ime": "Vanuatu", "jezik": "fr" },
    "TO": { "ime": "Tonga", "jezik": "en" },
    "NR": { "ime": "Nauru", "jezik": "en" },
    "PW": { "ime": "Palau", "jezik": "en" },
    "FM": { "ime": "Micronesia", "jezik": "en" },
    "JP": { "ime": "日本", "jezik": "ja" },
    "KR": { "ime": "대한민국", "jezik": "ko" },
    "CN": { "ime": "中国", "jezik": "zh" },
    "HK": { "ime": "香港", "jezik": "zh" },
    "MO": { "ime": "澳門", "jezik": "zh" },
    "TW": { "ime": "台灣", "jezik": "zh" },
    "SG": { "ime": "Singapore", "jezik": "en" },
    "MY": { "ime": "Malaysia", "jezik": "ms" },
    "ID": { "ime": "Indonesia", "jezik": "id" },
    "PH": { "ime": "Philippines", "jezik": "en" },
    "TH": { "ime": "ประเทศไทย", "jezik": "th" },
    "VN": { "ime": "Việt Nam", "jezik": "vi" },
    "KH": { "ime": "Cambodia", "jezik": "km" },
    "LA": { "ime": "Laos", "jezik": "lo" },
    "MM": { "ime": "Myanmar", "jezik": "my" },
    "BN": { "ime": "Brunei", "jezik": "ms" },
    "IN": { "ime": "India", "jezik": "en" },
    "PK": { "ime": "Pakistan", "jezik": "en" },
    "BD": { "ime": "Bangladesh", "jezik": "bn" },
    "LK": { "ime": "Sri Lanka", "jezik": "en" },
    "NP": { "ime": "Nepal", "jezik": "ne" },
    "BT": { "ime": "Bhutan", "jezik": "en" },
    "MV": { "ime": "Maldives", "jezik": "en" },
    "AF": { "ime": "Afghanistan", "jezik": "en" },
    "IL": { "ime": "Israel", "jezik": "he" },
    "JO": { "ime": "Jordan", "jezik": "ar" },
    "LB": { "ime": "Lebanon", "jezik": "ar" },
    "IQ": { "ime": "Iraq", "jezik": "ar" },
    "SA": { "ime": "Saudi Arabia", "jezik": "ar" },
    "AE": { "ime": "United Arab Emirates", "jezik": "ar" },
    "QA": { "ime": "Qatar", "jezik": "ar" },
    "KW": { "ime": "Kuwait", "jezik": "ar" },
    "BH": { "ime": "Bahrain", "jezik": "ar" },
    "OM": { "ime": "Oman", "jezik": "ar" },
    "YE": { "ime": "Yemen", "jezik": "ar" },
    "EG": { "ime": "Egypt", "jezik": "ar" },
    "LY": { "ime": "Libya", "jezik": "ar" },
    "TN": { "ime": "Tunisie", "jezik": "fr" },
    "DZ": { "ime": "Algérie", "jezik": "fr" },
    "MA": { "ime": "Maroc", "jezik": "fr" },
    "MR": { "ime": "Mauritanie", "jezik": "fr" },
    "SN": { "ime": "Sénégal", "jezik": "fr" },
    "ML": { "ime": "Mali", "jezik": "fr" },
    "NE": { "ime": "Niger", "jezik": "fr" },
    "BF": { "ime": "Burkina Faso", "jezik": "fr" },
    "CI": { "ime": "Côte d’Ivoire", "jezik": "fr" },
    "BJ": { "ime": "Bénin", "jezik": "fr" },
    "TD": { "ime": "Tchad", "jezik": "fr" },
    "CM": { "ime": "Cameroun", "jezik": "fr" },
    "GA": { "ime": "Gabon", "jezik": "fr" },
    "CG": { "ime": "Congo", "jezik": "fr" },
    "CD": { "ime": "RD Congo", "jezik": "fr" },
    "MG": { "ime": "Madagascar", "jezik": "fr" },
    "SC": { "ime": "Seychelles", "jezik": "en" },
    "MU": { "ime": "Mauritius", "jezik": "en" },
    "CV": { "ime": "Cabo Verde", "jezik": "pt" },
    "GW": { "ime": "Guiné-Bissau", "jezik": "pt" },
    "ST": { "ime": "São Tomé e Príncipe", "jezik": "pt" },
    "AO": { "ime": "Angola", "jezik": "pt" },
    "MZ": { "ime": "Moçambique", "jezik": "pt" },
    "GM": { "ime": "Gambia", "jezik": "en" },
    "GH": { "ime": "Ghana", "jezik": "en" },
    "LR": { "ime": "Liberia", "jezik": "en" },
    "SL": { "ime": "Sierra Leone", "jezik": "en" },
    "NG": { "ime": "Nigeria", "jezik": "en" },
    "KE": { "ime": "Kenya", "jezik": "en" },
    "UG": { "ime": "Uganda", "jezik": "en" },
    "TZ": { "ime": "Tanzania", "jezik": "en" },
    "RW": { "ime": "Rwanda", "jezik": "en" },
    "MW": { "ime": "Malawi", "jezik": "en" },
    "ZM": { "ime": "Zambia", "jezik": "en" },
    "ZW": { "ime": "Zimbabwe", "jezik": "en" },
    "BW": { "ime": "Botswana", "jezik": "en" },
    "NA": { "ime": "Namibia", "jezik": "en" },
    "SZ": { "ime": "Eswatini", "jezik": "en" },
    "ZA": { "ime": "South Africa", "jezik": "en" }
  }
};
