// Katalog izdelkov: [ime, kategorija, [znamke, ki obstajajo za ta izdelek], okvirna cena v €, enota]
// Cene so okvirne ocene (povprečje slovenskih trgovin); prave cene uvoziš v zavihku Cene.
window.NAKUPKO_PRODUCTS = [
  // Sadje in zelenjava
  ["Banane", "Sadje in zelenjava", ["Chiquita", "Dole", "Del Monte"], 1.69, "kg"],
  ["Jabolka", "Sadje in zelenjava", ["Zlati delišes", "Idared", "Gala", "Jonagold"], 1.49, "kg"],
  ["Hruške", "Sadje in zelenjava", ["Viljamovka", "Abate"], 2.49, "kg"],
  ["Pomaranče", "Sadje in zelenjava", [], 1.79, "kg"],
  ["Mandarine", "Sadje in zelenjava", [], 1.99, "kg"],
  ["Limone", "Sadje in zelenjava", [], 2.49, "kg"],
  ["Grozdje", "Sadje in zelenjava", [], 3.49, "kg"],
  ["Jagode", "Sadje in zelenjava", [], 3.99, "500 g"],
  ["Borovnice", "Sadje in zelenjava", [], 3.49, "250 g"],
  ["Kivi", "Sadje in zelenjava", ["Zespri"], 2.99, "kg"],
  ["Avokado", "Sadje in zelenjava", [], 1.29, "kos"],
  ["Ananas", "Sadje in zelenjava", ["Del Monte"], 2.49, "kos"],
  ["Lubenica", "Sadje in zelenjava", [], 0.99, "kg"],
  ["Paradižnik", "Sadje in zelenjava", [], 2.79, "kg"],
  ["Češnjev paradižnik", "Sadje in zelenjava", [], 2.29, "250 g"],
  ["Kumare", "Sadje in zelenjava", [], 1.99, "kg"],
  ["Paprika", "Sadje in zelenjava", [], 3.49, "kg"],
  ["Krompir", "Sadje in zelenjava", [], 1.29, "kg"],
  ["Sladki krompir", "Sadje in zelenjava", [], 2.99, "kg"],
  ["Čebula", "Sadje in zelenjava", [], 1.19, "kg"],
  ["Rdeča čebula", "Sadje in zelenjava", [], 1.69, "kg"],
  ["Česen", "Sadje in zelenjava", [], 0.89, "kos"],
  ["Korenje", "Sadje in zelenjava", [], 1.19, "kg"],
  ["Solata ledenka", "Sadje in zelenjava", [], 1.19, "kos"],
  ["Rukola", "Sadje in zelenjava", [], 1.49, "125 g"],
  ["Motovilec", "Sadje in zelenjava", [], 1.79, "125 g"],
  ["Špinača", "Sadje in zelenjava", [], 1.99, "250 g"],
  ["Brokoli", "Sadje in zelenjava", [], 1.69, "kos"],
  ["Cvetača", "Sadje in zelenjava", [], 1.99, "kos"],
  ["Bučke", "Sadje in zelenjava", [], 2.49, "kg"],
  ["Jajčevci", "Sadje in zelenjava", [], 2.99, "kg"],
  ["Gobe šampinjoni", "Sadje in zelenjava", [], 1.89, "250 g"],
  ["Zelje", "Sadje in zelenjava", [], 0.99, "kg"],
  ["Por", "Sadje in zelenjava", [], 2.49, "kg"],
  ["Ingver", "Sadje in zelenjava", [], 0.79, "100 g"],
  ["Peteršilj", "Sadje in zelenjava", [], 0.99, "šopek"],
  ["Bazilika", "Sadje in zelenjava", [], 1.79, "lonček"],
  ["Koruza v pločevinki", "Sadje in zelenjava", ["Bonduelle", "Podravka"], 1.29, "340 g"],

  // Mleko in mlečni izdelki
  ["Mleko", "Mlečni izdelki", ["Ljubljanske mlekarne › 3,5 %", "Ljubljanske mlekarne › 1,5 %", "Pomurske mlekarne › 3,5 %", "Pomurske mlekarne › 1,5 %", "Celeia › 3,5 %", "Celeia › 1,5 %", "Kmečko mleko", "Alpsko mleko"], 1.19, "1 l"],
  ["Mleko brez laktoze", "Mlečni izdelki", ["Ljubljanske mlekarne", "Zbregov"], 1.69, "1 l"],
  ["Ovseni napitek", "Mlečni izdelki", ["Oatly", "Alpro"], 2.49, "1 l"],
  ["Sojin napitek", "Mlečni izdelki", ["Alpro"], 2.29, "1 l"],
  ["Jogurt navadni", "Mlečni izdelki", ["Ljubljanske mlekarne", "Celeia", "Pomurske mlekarne"], 0.69, "180 g"],
  ["Sadni jogurt", "Mlečni izdelki", ["Ego", "Zbregov", "Müller", "Danone"], 0.79, "150 g"],
  ["Grški jogurt", "Mlečni izdelki", ["Olympus", "Fage", "Ljubljanske mlekarne"], 1.49, "170 g"],
  ["Skyr", "Mlečni izdelki", ["Siggi's", "Ljubljanske mlekarne"], 1.29, "150 g"],
  ["Kefir", "Mlečni izdelki", ["Ljubljanske mlekarne", "Celeia"], 0.99, "500 ml"],
  ["Kisla smetana", "Mlečni izdelki", ["Ljubljanske mlekarne", "Pomurske mlekarne"], 0.89, "200 g"],
  ["Sladka smetana", "Mlečni izdelki", ["Ljubljanske mlekarne", "Meggle"], 1.49, "200 ml"],
  ["Maslo", "Mlečni izdelki", ["Ljubljanske mlekarne", "Pomurske mlekarne", "Meggle", "Kerrygold"], 2.49, "250 g"],
  ["Skuta", "Mlečni izdelki", ["Ljubljanske mlekarne", "Celeia"], 1.39, "250 g"],
  ["Mozzarella", "Mlečni izdelki", ["Galbani", "Zott"], 1.29, "125 g"],
  ["Sir Gauda", "Mlečni izdelki", ["Pomurske mlekarne", "Ljubljanske mlekarne"], 2.29, "200 g"],
  ["Sir Edamec", "Mlečni izdelki", ["Pomurske mlekarne", "Ljubljanske mlekarne"], 2.19, "200 g"],
  ["Sir Trapist", "Mlečni izdelki", ["Pomurske mlekarne"], 2.29, "200 g"],
  ["Parmezan", "Mlečni izdelki", ["Parmareggio", "Grana Padano"], 3.49, "150 g"],
  ["Feta", "Mlečni izdelki", ["Dodoni", "Salakis"], 2.49, "200 g"],
  ["Sirni namaz", "Mlečni izdelki", ["Philadelphia", "Président"], 1.99, "150 g"],
  ["Topljeni sir", "Mlečni izdelki", ["Zdenka", "La vache qui rit"], 1.79, "140 g"],
  ["Puding", "Mlečni izdelki", ["Ego", "Paladin", "Dr. Oetker"], 0.89, "kos"],
  ["Mlečni riž", "Mlečni izdelki", ["Müller", "Ego"], 0.99, "200 g"],
  ["Jajca", "Mlečni izdelki", ["Jata", "Panvita", "Kmečka"], 2.89, "10 kos"],

  // Meso in ribe
  ["Piščančji file", "Meso in ribe", ["Pivka", "Perutnina Ptuj"], 10.99, "kg"],
  ["Piščančja bedra", "Meso in ribe", ["Pivka", "Perutnina Ptuj"], 5.49, "kg"],
  ["Cel piščanec", "Meso in ribe", ["Pivka", "Perutnina Ptuj"], 4.49, "kg"],
  ["Mleto meso", "Meso in ribe", [], 8.99, "kg"],
  ["Svinjski kotleti", "Meso in ribe", [], 8.49, "kg"],
  ["Goveji zrezki", "Meso in ribe", [], 16.99, "kg"],
  ["Puranji file", "Meso in ribe", ["Pivka", "Perutnina Ptuj"], 12.99, "kg"],
  ["Hrenovke", "Meso in ribe", ["Pivka", "Perutnina Ptuj", "Košaki", "Celjske mesnine"], 2.29, "300 g"],
  ["Kranjska klobasa", "Meso in ribe", ["Celjske mesnine", "Košaki", "Kras"], 3.99, "2 kos"],
  ["Pršut", "Meso in ribe", ["Kras", "Celjske mesnine"], 3.49, "80 g"],
  ["Šunka", "Meso in ribe", ["Pivka", "Celjske mesnine", "Gorenjka", "Kras"], 1.99, "100 g"],
  ["Salama", "Meso in ribe", ["Pivka", "Celjske mesnine", "Gavrilović", "Kras"], 1.79, "100 g"],
  ["Slanina", "Meso in ribe", ["Kras", "Celjske mesnine"], 2.49, "150 g"],
  ["Pašteta", "Meso in ribe", ["Argeta", "Gavrilović", "Podravka"], 1.39, "95 g"],
  ["Tuna v pločevinki", "Meso in ribe", ["Rio Mare", "Calvo", "Delamaris"], 2.29, "160 g"],
  ["Sardine", "Meso in ribe", ["Delamaris", "Eva"], 1.49, "115 g"],
  ["Losos", "Meso in ribe", [], 4.99, "250 g"],
  ["Ribje palčke", "Meso in ribe", ["Iglo", "Frikom"], 3.49, "300 g"],

  // Kruh in pekovski izdelki
  ["Kruh beli", "Kruh in pecivo", ["Žito", "Pekarna Pečjak", "Mlinotest"], 1.89, "500 g"],
  ["Kruh polnozrnati", "Kruh in pecivo", ["Žito", "Pekarna Pečjak", "Mlinotest"], 2.39, "500 g"],
  ["Toast kruh", "Kruh in pecivo", ["Žito", "Harry's", "Golden Toast"], 1.79, "500 g"],
  ["Žemlje", "Kruh in pecivo", [], 0.29, "kos"],
  ["Bageta", "Kruh in pecivo", [], 0.99, "kos"],
  ["Rogljiček", "Kruh in pecivo", [], 0.69, "kos"],
  ["Burek", "Kruh in pecivo", [], 2.49, "kos"],
  ["Tortilje", "Kruh in pecivo", ["Old El Paso", "Mission"], 2.29, "8 kos"],
  ["Prepečenec", "Kruh in pecivo", ["Žito", "Brumbo"], 1.49, "kos"],

  // Shramba
  ["Testenine špageti", "Shramba", ["Barilla", "Mlinotest", "Zlato polje", "De Cecco"], 1.29, "500 g"],
  ["Testenine peresniki", "Shramba", ["Barilla", "Mlinotest", "Zlato polje"], 1.29, "500 g"],
  ["Riž", "Shramba", ["Zlato polje", "Uncle Ben's", "Scotti"], 1.99, "1 kg"],
  ["Riž basmati", "Shramba", ["Tilda", "Zlato polje"], 2.99, "1 kg"],
  ["Moka bela", "Shramba", ["Mlinotest", "Žito"], 0.99, "1 kg"],
  ["Moka polnozrnata", "Shramba", ["Mlinotest", "Žito"], 1.49, "1 kg"],
  ["Koruzni zdrob (polenta)", "Shramba", ["Mlinotest", "Zlato polje"], 1.29, "500 g"],
  ["Sladkor", "Shramba", ["Agrana", "Viljem Julijan"], 1.19, "1 kg"],
  ["Sol", "Shramba", ["Piranske soline", "Solana Tuzla"], 0.69, "1 kg"],
  ["Olje sončnično", "Shramba", ["Zvijezda", "Floriol", "Iso"], 2.29, "1 l"],
  ["Olivno olje", "Shramba", ["Monini", "Bertolli", "Farchioni"], 9.99, "750 ml"],
  ["Kis", "Shramba", ["Zvijezda", "Mercator"], 0.99, "1 l"],
  ["Balzamični kis", "Shramba", ["Ponti", "Monari Federzoni"], 2.99, "500 ml"],
  ["Paradižnikova mezga", "Shramba", ["Mutti", "Podravka", "Pomi"], 1.29, "500 g"],
  ["Pelati", "Shramba", ["Mutti", "Cirio"], 1.39, "400 g"],
  ["Paradižnikov koncentrat", "Shramba", ["Mutti", "Podravka", "Pomi", "Cirio", "S-Budget"], 1.19, "200 g"],
  ["Omaka za testenine", "Shramba", ["Barilla", "Dolmio", "Podravka"], 2.49, "400 g"],
  ["Pesto", "Shramba", ["Barilla", "Sacla"], 2.99, "190 g"],
  ["Fižol v pločevinki", "Shramba", ["Podravka", "Bonduelle"], 1.19, "400 g"],
  ["Čičerika", "Shramba", ["Bonduelle", "Podravka"], 1.29, "400 g"],
  ["Leča", "Shramba", ["Zlato polje"], 2.49, "500 g"],
  ["Ovseni kosmiči", "Shramba", ["Zlato polje", "Kölln", "Natura"], 1.49, "500 g"],
  ["Kosmiči za zajtrk", "Shramba", ["Nestlé", "Kellogg's", "Lino"], 3.49, "375 g"],
  ["Muesli", "Shramba", ["Kölln", "Natura", "Dr. Oetker Vitalis"], 3.29, "500 g"],
  ["Med", "Shramba", ["Medex", "Žito"], 6.99, "450 g"],
  ["Marmelada", "Shramba", ["Podravka", "Zvijezda", "Darbo", "Bonne Maman"], 2.49, "370 g"],
  ["Lešnikov namaz", "Shramba", ["Nutella", "Lino lada", "Nougatti"], 3.99, "400 g"],
  ["Arašidovo maslo", "Shramba", ["Nutrilife", "Sun Snacks"], 3.49, "350 g"],
  ["Kvas (suhi)", "Shramba", ["Dr. Oetker", "Podravka"], 0.49, "3 vrečke"],
  ["Kvas (sveži)", "Shramba", [], 0.29, "42 g"],
  ["Pecilni prašek", "Shramba", ["Dr. Oetker", "Podravka"], 0.49, "3 vrečke"],
  ["Vanilijev sladkor", "Shramba", ["Dr. Oetker", "Podravka"], 0.59, "3 vrečke"],
  ["Kakav v prahu", "Shramba", ["Dr. Oetker", "Kraš"], 2.49, "100 g"],
  ["Čokolada za kuhanje", "Shramba", ["Dr. Oetker", "Gorenjka", "Kraš"], 1.99, "200 g"],
  ["Kokosovo mleko", "Shramba", ["Thai Kitchen", "Kingsway"], 1.99, "400 ml"],
  ["Sojina omaka", "Shramba", ["Kikkoman", "Kingsway"], 2.99, "250 ml"],
  ["Kari (curry) začimba", "Shramba", ["Kotányi", "Podravka", "Šmarna"], 1.49, "kos"],
  ["Kari pasta", "Shramba", ["Thai Kitchen", "Patak's"], 3.29, "kos"],
  ["Poper", "Shramba", ["Kotányi", "Šmarna", "Podravka"], 1.69, "kos"],
  ["Paprika mleta", "Shramba", ["Kotányi", "Šmarna", "Podravka"], 1.49, "kos"],
  ["Origano", "Shramba", ["Kotányi", "Šmarna"], 1.29, "kos"],
  ["Cimet", "Shramba", ["Kotányi", "Šmarna"], 1.29, "kos"],
  ["Vegeta", "Shramba", ["Podravka"], 2.49, "500 g"],
  ["Jušna kocka", "Shramba", ["Knorr", "Podravka", "Maggi"], 1.49, "kos"],
  ["Instant juha", "Shramba", ["Knorr", "Podravka", "Maggi"], 0.99, "kos"],
  ["Ketchup", "Shramba", ["Heinz", "Podravka", "Zvijezda"], 2.29, "500 g"],
  ["Majoneza", "Shramba", ["Thomy", "Zvijezda", "Hellmann's"], 2.19, "250 ml"],
  ["Gorčica", "Shramba", ["Thomy", "Podravka", "Kühne"], 1.29, "kos"],
  ["Kisle kumarice", "Shramba", ["Kühne", "Podravka", "Eta"], 1.99, "kos"],
  ["Ajvar", "Shramba", ["Podravka", "Zvijezda"], 2.49, "350 g"],
  ["Olive", "Shramba", ["Podravka", "Bonduelle"], 1.99, "kos"],

  // Pijače
  ["Voda", "Pijače", ["Zala", "Costella", "Dana"], 0.49, "1,5 l"],
  ["Mineralna voda", "Pijače", ["Radenska", "Donat Mg", "Rogaška"], 0.89, "1,5 l"],
  ["Cedevita", "Pijače", ["Cedevita"], 4.99, "455 g"],
  ["Sirup", "Pijače", ["Fructal", "Dana", "Pfanner"], 3.49, "1 l"],
  ["Sok pomarančni", "Pijače", ["Fructal", "Pfanner", "Happy Day", "Dana"], 1.99, "1 l"],
  ["Sok jabolčni", "Pijače", ["Fructal", "Pfanner", "Happy Day"], 1.79, "1 l"],
  ["Ledeni čaj", "Pijače", ["Pfanner", "Fructal", "Fuze Tea"], 1.49, "1,5 l"],
  ["Coca-Cola", "Pijače", ["Coca-Cola"], 1.99, "1,5 l"],
  ["Coca-Cola Zero", "Pijače", ["Coca-Cola"], 1.99, "1,5 l"],
  ["Fanta", "Pijače", ["Fanta"], 1.89, "1,5 l"],
  ["Sprite", "Pijače", ["Sprite"], 1.89, "1,5 l"],
  ["Cockta", "Pijače", ["Cockta"], 1.79, "1,5 l"],
  ["Energijska pijača", "Pijače", ["Red Bull › Original", "Red Bull › Sugarfree", "Red Bull › Zero", "Red Bull › Red Edition", "Monster › Original", "Monster › Ultra White", "Monster › Mango Loco", "Monster › Ultra Paradise", "Hell › Classic", "Hell › Zero"], 1.49, "250 ml"],
  ["Kava mleta", "Pijače", ["Barcaffe", "Illy", "Lavazza", "Jacobs"], 4.99, "250 g"],
  ["Kava v zrnju", "Pijače", ["Barcaffe", "Lavazza", "Illy", "Tchibo"], 9.99, "500 g"],
  ["Kavne kapsule", "Pijače", ["Nespresso", "Barcaffe", "Lavazza", "Dolce Gusto"], 4.49, "10 kos"],
  ["Instant kava", "Pijače", ["Nescafé", "Jacobs", "Barcaffe"], 4.99, "kos"],
  ["Čaj", "Pijače", ["1001 cvet", "Teekanne", "Lipton"], 1.99, "20 vrečk"],
  ["Pivo", "Pijače", ["Laško › Zlatorog", "Laško › Club", "Laško › Temno", "Union › Svetlo", "Union › Temno", "Heineken"], 1.19, "0,5 l"],
  ["Pivo (paket)", "Pijače", ["Laško › Zlatorog", "Laško › Club", "Laško › Temno", "Union › Svetlo", "Union › Temno", "Heineken"], 6.49, "6 x 0,5 l"],
  ["Radler", "Pijače", ["Laško", "Union"], 1.19, "0,5 l"],
  ["Cider", "Pijače", ["Somersby", "Strongbow"], 1.79, "0,5 l"],
  ["Vino belo", "Pijače", ["Goriška Brda", "Vinakoper", "Puklavec", "Radgonske gorice"], 5.99, "0,75 l"],
  ["Vino rdeče", "Pijače", ["Vinakoper", "Goriška Brda", "Puklavec"], 6.49, "0,75 l"],
  ["Penina", "Pijače", ["Radgonske gorice", "Bjana"], 9.99, "0,75 l"],

  // Sladko in slano
  ["Čokolada", "Prigrizki", ["Milka", "Gorenjka", "Lindt", "Ritter Sport"], 1.99, "100 g"],
  ["Piškoti", "Prigrizki", ["Kraš", "Leibniz", "Oreo", "Domaćica"], 1.79, "kos"],
  ["Napolitanke", "Prigrizki", ["Kraš", "Loacker", "Manner"], 1.69, "kos"],
  ["Čokolino", "Shramba", ["Podravka"], 2.99, "400 g"],
  ["Čips", "Prigrizki", ["Chio", "Pringles", "Lay's", "Pomurka"], 2.29, "kos"],
  ["Smoki", "Prigrizki", ["Štark"], 1.29, "kos"],
  ["Palčke slane", "Prigrizki", ["Štark", "Lorenz"], 0.99, "kos"],
  ["Arašidi", "Prigrizki", ["Ültje", "Felix"], 1.99, "200 g"],
  ["Mešanica oreščkov", "Prigrizki", ["Ültje", "Seeberger"], 3.49, "200 g"],
  ["Bonboni", "Prigrizki", ["Haribo", "Mentos", "Bayersdorf"], 1.49, "kos"],
  ["Sladoled", "Prigrizki", ["Ljubljanske mlekarne", "Algida", "Frikom"], 4.49, "1 l"],
  ["Proteinska ploščica", "Prigrizki", ["Barebells › Caramel Cashew", "Barebells › Salty Peanut", "Barebells › Cookies & Cream", "Barebells › Hazelnut Nougat", "Barebells › White Chocolate Almond", "Grenade › Cookies & Cream", "Grenade › Chocolate Chip Salted Caramel", "Grenade › White Chocolate Cookie", "Corny", "Nutrilife", "Proteini.si", "THE Nutrition"], 2.29, "kos"],

  // Zamrznjeno
  ["Pizza zamrznjena", "Zamrznjeno", ["Dr. Oetker", "Wagner", "Mlinotest"], 3.49, "kos"],
  ["Pomfri", "Zamrznjeno", ["McCain", "Frikom"], 2.49, "750 g"],
  ["Zamrznjena zelenjava", "Zamrznjeno", ["Iglo", "Frikom", "Ledo"], 1.99, "450 g"],
  ["Zamrznjeni grah", "Zamrznjeno", ["Iglo", "Frikom", "Ledo"], 1.69, "450 g"],
  ["Njoki", "Zamrznjeno", ["Mlinotest", "Fragolina"], 1.79, "500 g"],
  ["Ravioli", "Zamrznjeno", ["Mlinotest", "Rana"], 2.99, "250 g"],

  // Gospodinjstvo
  ["Toaletni papir", "Gospodinjstvo", ["Paloma", "Zewa", "Familia"], 4.49, "10 rol"],
  ["Papirnate brisače", "Gospodinjstvo", ["Paloma", "Zewa", "Familia"], 2.49, "2 roli"],
  ["Robčki", "Gospodinjstvo", ["Paloma", "Tempo", "Kleenex"], 1.99, "kos"],
  ["Detergent za pranje perila", "Gospodinjstvo", ["Persil › Color", "Persil › Universal", "Persil › Sensitive", "Ariel › Color", "Ariel › Universal", "Ariel › Sensitive", "Faks › Color", "Faks › Universal", "Faks › Sensitive", "Formil (Lidl)", "Tandil (Hofer)"], 11.99, "tekoči, kos"],
  ["Pralni prašek", "Gospodinjstvo", ["Ariel › Color", "Ariel › Universal", "Ariel › Sensitive", "Persil › Color", "Persil › Universal", "Persil › Sensitive", "Bonux › Color", "Bonux › Universal", "Faks › Color", "Faks › Universal", "Biopon", "Formil (Lidl)", "Tandil (Hofer)"], 12.99, "kos"],
  ["Mehčalec", "Gospodinjstvo", ["Silan › Fresh Sky", "Silan › Sensitive", "Silan › Aromatherapy", "Lenor › Spring Awakening", "Lenor › Gold Orchid", "Lenor › Sensitive", "Coccolino", "Formil (Lidl)", "Tandil (Hofer)"], 3.99, "kos"],
  ["Dišeči biseri za perilo", "Gospodinjstvo", ["Lenor Unstoppables", "Silan"], 7.99, "kos"],
  ["Detergent za posodo", "Gospodinjstvo", ["Pril", "Jar", "Fairy"], 1.99, "kos"],
  ["Tablete za pomivalni stroj", "Gospodinjstvo", ["Finish", "Somat", "Fairy"], 9.99, "kos"],
  ["Čistilo za kopalnico", "Gospodinjstvo", ["Cif", "Bref", "Domestos"], 2.99, "kos"],
  ["Vrečke za smeti", "Gospodinjstvo", ["Paloma", "Swirl"], 2.29, "kos"],
  ["Aluminijasta folija", "Gospodinjstvo", ["Paloma", "Toppits"], 2.49, "kos"],
  ["Gobice za posodo", "Gospodinjstvo", ["Spontex", "Vileda"], 1.49, "kos"],
  ["Baterije", "Gospodinjstvo", ["Duracell", "Varta", "Energizer"], 5.99, "4 kos"],

  // Higiena
  ["Zobna pasta", "Higiena", ["Colgate", "Sensodyne", "Elmex", "Signal"], 2.49, "75 ml"],
  ["Zobna ščetka", "Higiena", ["Colgate", "Oral-B", "Elmex"], 2.49, "kos"],
  ["Šampon", "Higiena", ["Head & Shoulders", "Garnier Fructis", "Schauma", "Elseve"], 3.99, "kos"],
  ["Gel za tuširanje", "Higiena", ["Fa", "Nivea", "Dove", "Palmolive"], 2.49, "kos"],
  ["Milo", "Higiena", ["Dove", "Palmolive", "Fa"], 1.29, "kos"],
  ["Dezodorant", "Higiena", ["Nivea", "Rexona", "Dove", "Axe"], 3.29, "kos"],
  ["Brivniki", "Higiena", ["Gillette", "Wilkinson"], 8.99, "kos"],
  ["Pena za britje", "Higiena", ["Gillette", "Nivea"], 3.49, "kos"],
  ["Krema za roke", "Higiena", ["Nivea", "Neutrogena", "Garnier"], 2.99, "kos"],
  ["Vložki", "Higiena", ["Always", "Libresse"], 3.49, "kos"],
  ["Plenice", "Higiena", ["Pampers", "Huggies", "Libero"], 12.99, "kos"],
  ["Vlažilni robčki", "Higiena", ["Pampers", "Huggies", "Paloma"], 1.99, "kos"],

  // Brez glutena (okvirne cene; Schär je v Sparu, Mercatorju in Tušu)
  ["Testenine brez glutena", "Brez glutena", ["Schär", "Barilla", "Le Veneziane", "Mlinotest"], 2.79, "500 g"],
  ["Testenine brez glutena peresniki", "Brez glutena", ["Schär", "Barilla", "Le Veneziane"], 2.79, "500 g"],
  ["Testenine brez glutena fusilli", "Brez glutena", ["Schär", "Barilla", "Le Veneziane"], 2.79, "500 g"],
  ["Kruh brez glutena", "Brez glutena", ["Schär", "Bezgluten"], 3.99, "250 g"],
  ["Žemlje brez glutena", "Brez glutena", ["Schär"], 3.49, "4 kos"],
  ["Toast kruh brez glutena", "Brez glutena", ["Schär"], 3.79, "400 g"],
  ["Moka brez glutena", "Brez glutena", ["Schär Mix B", "Schär Mix C", "Bezgluten"], 3.99, "1 kg"],
  ["Piškoti brez glutena", "Brez glutena", ["Schär", "Bezgluten"], 2.99, "200 g"],
  ["Krekerji brez glutena", "Brez glutena", ["Schär"], 2.49, "210 g"],
  ["Grisini brez glutena", "Brez glutena", ["Schär"], 2.69, "150 g"],
  ["Kosmiči brez glutena", "Brez glutena", ["Schär", "Nestlé"], 3.99, "300 g"],
  ["Ovseni kosmiči brez glutena", "Brez glutena", ["Schär", "Natura"], 3.49, "500 g"],
  ["Pica testo brez glutena", "Brez glutena", ["Schär"], 3.99, "kos"],
  ["Pica brez glutena (zamrznjena)", "Brez glutena", ["Schär", "Dr. Oetker"], 4.99, "kos"],
  ["Lazanja plošče brez glutena", "Brez glutena", ["Schär", "Barilla"], 3.29, "250 g"],
  ["Pivo brez glutena", "Brez glutena", ["Daura Damm", "Schär"], 1.99, "0,33 l"],
  ["Čokoladne ploščice brez glutena", "Brez glutena", ["Schär Twin Bar", "Schär Milly"], 2.49, "kos"],
  ["Drobtine brez glutena", "Brez glutena", ["Schär"], 2.49, "300 g"],
  // Tobak (cene so v Sloveniji enake v vseh trgovinah; vir: Kompas shop cenik 1. 6. 2026, secret-slovenia.com)
  ["Cigarete Marlboro", "Tobak", ["Red", "Gold", "Touch", "Advance Blue"], 6.00, "20 kos", true],
  ["Cigarete Winston", "Tobak", ["Classic", "Blue", "Silver", "XStyle Blue"], 5.50, "20 kos", true],
  ["Cigarete Camel", "Tobak", ["Yellow", "Blue", "Essential Blue"], 5.60, "20 kos", true],
  ["Cigarete Chesterfield", "Tobak", ["Blue", "Red"], 5.50, "20 kos", true],
  ["Cigarete L&M", "Tobak", ["Blue Label", "Red Label"], 5.50, "20 kos", true],
  ["Cigarete Davidoff", "Tobak", ["Gold", "Reach Blue", "Reach Silver"], 6.10, "20 kos", true],
  ["Cigarete Philip Morris", "Tobak", ["Supreme", "Supreme 100's"], 5.20, "20 kos", true],
  ["Cigarete Lucky Strike", "Tobak", ["Red", "Blue"], 5.60, "20 kos", true],
  ["Cigarete West", "Tobak", ["Red", "Blue", "Silver"], 5.60, "20 kos", true],
  ["Cigarete Boss", "Tobak", ["Classic", "Blue", "Silver", "Gold"], 5.50, "20 kos", true],
  ["Cigarete Eve", "Tobak", ["Red Divine", "Blue Mystique"], 5.50, "20 kos", true],
  ["Cigarete Benson & Hedges", "Tobak", ["Red", "Blue"], 5.20, "20 kos", true],
  ["Cigarete Austin", "Tobak", ["Red", "Blue"], 4.80, "20 kos", true],
  ["Tobačne palčke (IQOS)", "Tobak", ["Terea › Amber", "Terea › Bronze", "Terea › Russet", "Terea › Sienna", "Terea › Silver", "Terea › Soft Fuse", "Terea › Teak", "Terea › Turquoise", "Terea › Yellow", "Heets › Bronze", "Heets › Sienna", "Heets › Silver", "Heets › Turquoise", "Heets › Yellow"], 5.00, "20 kos", true],
  ["Tobak za zvijanje", "Tobak", ["Pueblo", "Golden Virginia", "Drum", "Chesterfield"], 9.50, "30 g", true],
  ["Papirčki za zvijanje", "Tobak", ["OCB", "Rizla", "Smoking"], 0.99, "kos"],
  ["Filtri za zvijanje", "Tobak", ["OCB", "Rizla", "Smoking"], 1.49, "kos"],
  ["Vžigalnik", "Tobak", ["BIC", "Clipper"], 1.49, "kos"],
  ["Vžigalice", "Tobak", [], 0.49, "kos"],

  // Hišni ljubljenčki
  ["Hrana za mačke", "Ljubljenčki", ["Whiskas", "Felix", "Sheba", "Purina"], 0.79, "kos"],
  ["Hrana za pse", "Ljubljenčki", ["Pedigree", "Purina", "Chappi"], 1.49, "kos"],
  ["Pesek za mačke", "Ljubljenčki", ["Catsan", "Cat's Best"], 6.99, "kos"]
];
