// Dodatni izdelki (okvirne cene)
window.NAKUPKO_PRODUCTS = (window.NAKUPKO_PRODUCTS || []).concat([
  // Sadje in zelenjava
  ["Breskve", "Sadje in zelenjava", [], 2.49, "kg"],
  ["Nektarine", "Sadje in zelenjava", [], 2.49, "kg"],
  ["Marelice", "Sadje in zelenjava", [], 3.49, "kg"],
  ["Slive", "Sadje in zelenjava", [], 1.99, "kg"],
  ["Češnje", "Sadje in zelenjava", [], 5.99, "kg"],
  ["Maline", "Sadje in zelenjava", [], 2.99, "125 g"],
  ["Robide", "Sadje in zelenjava", [], 2.99, "125 g"],
  ["Melona", "Sadje in zelenjava", [], 1.99, "kos"],
  ["Mango", "Sadje in zelenjava", [], 1.99, "kos"],
  ["Granatno jabolko", "Sadje in zelenjava", [], 1.49, "kos"],
  ["Grenivke", "Sadje in zelenjava", [], 2.29, "kg"],
  ["Limete", "Sadje in zelenjava", [], 0.49, "kos"],
  ["Fige", "Sadje in zelenjava", [], 0.79, "kos"],
  ["Kaki", "Sadje in zelenjava", [], 2.49, "kg"],
  ["Kokos", "Sadje in zelenjava", [], 1.99, "kos"],
  ["Pesa", "Sadje in zelenjava", [], 1.49, "kg"],
  ["Kuhana rdeča pesa", "Sadje in zelenjava", ["Natura", "Lidl"], 1.29, "500 g"],
  ["Redkvica", "Sadje in zelenjava", [], 0.99, "šopek"],
  ["Zelena (gomolj)", "Sadje in zelenjava", [], 1.99, "kg"],
  ["Koleraba", "Sadje in zelenjava", [], 0.79, "kos"],
  ["Ohrovt", "Sadje in zelenjava", [], 1.99, "kg"],
  ["Rdeče zelje", "Sadje in zelenjava", [], 1.29, "kg"],
  ["Kislo zelje", "Sadje in zelenjava", ["Ekoren", "Mercator"], 1.79, "500 g"],
  ["Kisla repa", "Sadje in zelenjava", ["Ekoren"], 1.79, "500 g"],
  ["Mlada čebula", "Sadje in zelenjava", [], 0.99, "šopek"],
  ["Šalotka", "Sadje in zelenjava", [], 2.49, "250 g"],
  ["Radič", "Sadje in zelenjava", [], 4.99, "kg"],
  ["Endivija", "Sadje in zelenjava", [], 1.49, "kos"],
  ["Mešana solata", "Sadje in zelenjava", ["Florette", "Lidl"], 1.99, "150 g"],
  ["Kristalka", "Sadje in zelenjava", [], 0.99, "kos"],
  ["Stročji fižol", "Sadje in zelenjava", [], 3.99, "kg"],
  ["Beluši", "Sadje in zelenjava", [], 4.99, "500 g"],
  ["Artičoke", "Sadje in zelenjava", [], 1.49, "kos"],
  ["Bučka hokaido", "Sadje in zelenjava", [], 1.99, "kg"],
  ["Ostra paprika", "Sadje in zelenjava", [], 1.29, "100 g"],
  ["Paradižnik na trti", "Sadje in zelenjava", [], 3.49, "kg"],
  ["Gobe bukovke", "Sadje in zelenjava", [], 2.49, "200 g"],
  ["Šitake", "Sadje in zelenjava", [], 2.99, "150 g"],
  ["Komarček", "Sadje in zelenjava", [], 0.99, "kos"],
  ["Hren", "Sadje in zelenjava", [], 1.49, "kos"],
  ["Pastinak", "Sadje in zelenjava", [], 2.99, "kg"],
  ["Peteršiljeva korenina", "Sadje in zelenjava", [], 3.49, "kg"],
  ["Drobnjak", "Sadje in zelenjava", [], 0.99, "šopek"],
  ["Koper", "Sadje in zelenjava", [], 0.99, "šopek"],
  ["Meta", "Sadje in zelenjava", [], 1.79, "lonček"],
  ["Rožmarin", "Sadje in zelenjava", [], 1.79, "lonček"],
  ["Timijan", "Sadje in zelenjava", [], 1.79, "lonček"],
  ["Koriander (svež)", "Sadje in zelenjava", [], 0.99, "šopek"],
  ["Kalčki", "Sadje in zelenjava", [], 1.49, "100 g"],
  ["Suhe slive", "Sadje in zelenjava", ["Lidl", "Mercator"], 2.49, "200 g"],
  ["Rozine", "Sadje in zelenjava", ["Mercator", "Spar"], 1.49, "200 g"],
  ["Suhe marelice", "Sadje in zelenjava", ["Lidl", "Spar"], 2.99, "200 g"],
  ["Datlji", "Sadje in zelenjava", ["Lidl", "Spar"], 2.49, "200 g"],

  // Kruh in pecivo
  ["Kruh črni", "Kruh in pecivo", ["Žito", "Pekarna Pečjak"], 2.29, "500 g"],
  ["Kruh ržen", "Kruh in pecivo", ["Žito", "Pekarna Pečjak"], 2.59, "500 g"],
  ["Kruh koruzni", "Kruh in pecivo", ["Žito"], 2.49, "500 g"],
  ["Kruh s semeni", "Kruh in pecivo", ["Žito", "Pekarna Pečjak"], 2.79, "500 g"],
  ["Kruh ajdov", "Kruh in pecivo", ["Žito"], 2.99, "500 g"],
  ["Mlečna štručka", "Kruh in pecivo", ["Žito"], 0.59, "kos"],
  ["Kajzerica", "Kruh in pecivo", [], 0.35, "kos"],
  ["Ciabatta", "Kruh in pecivo", [], 1.29, "kos"],
  ["Hamburger žemlje", "Kruh in pecivo", ["Harry's", "Lidl"], 1.99, "4 kos"],
  ["Hot dog štručke", "Kruh in pecivo", ["Harry's"], 1.79, "6 kos"],
  ["Pita kruh", "Kruh in pecivo", [], 1.49, "4 kos"],
  ["Krof", "Kruh in pecivo", [], 0.89, "kos"],
  ["Potica orehova", "Kruh in pecivo", ["Žito", "Pekarna Pečjak"], 8.99, "500 g"],
  ["Pletenica", "Kruh in pecivo", ["Žito"], 2.49, "kos"],
  ["Štruklji", "Kruh in pecivo", ["Pekarna Pečjak"], 3.99, "500 g"],
  ["Zavitek z jabolki", "Kruh in pecivo", ["Pekarna Pečjak"], 2.99, "kos"],
  ["Pirin kruh", "Kruh in pecivo", ["Žito"], 2.99, "500 g"],
  ["Krušne drobtine", "Kruh in pecivo", ["Žito", "Mercator"], 0.99, "500 g"],
  ["Krekerji", "Kruh in pecivo", ["Tuc", "Mercator"], 1.29, "100 g"],
  ["Riževi vafli", "Kruh in pecivo", ["Mercator", "Lidl"], 0.99, "100 g"],
  ["Lističi za lazanjo", "Kruh in pecivo", ["Barilla", "Mercator"], 1.99, "500 g"],
  ["Listnato testo", "Kruh in pecivo", ["Pekarna Pečjak", "Lidl"], 1.69, "500 g"],
  ["Vlečeno testo", "Kruh in pecivo", ["Pekarna Pečjak"], 2.29, "500 g"],
  ["Testo za pico", "Kruh in pecivo", ["Pekarna Pečjak", "Lidl"], 1.69, "400 g"],

  // Mlečni izdelki
  ["Čokoladno mleko", "Mlečni izdelki", ["Ljubljanske mlekarne", "Pomurske mlekarne"], 0.99, "0,5 l"],
  ["Kavni napitek", "Mlečni izdelki", ["Ljubljanske mlekarne", "Barcaffe"], 1.19, "250 ml"],
  ["Mandljev napitek", "Mlečni izdelki", ["Alpro"], 2.49, "1 l"],
  ["Rižev napitek", "Mlečni izdelki", ["Alpro", "Lidl"], 1.99, "1 l"],
  ["Tekoči jogurt", "Mlečni izdelki", ["Ljubljanske mlekarne", "Celeia"], 1.09, "500 g"],
  ["Probiotični jogurt", "Mlečni izdelki", ["Activia", "LCA"], 0.99, "125 g"],
  ["Lučka jogurt", "Mlečni izdelki", ["Ljubljanske mlekarne"], 0.59, "150 g"],
  ["Pinjenec", "Mlečni izdelki", ["Ljubljanske mlekarne"], 0.89, "500 ml"],
  ["Sladka smetana v spreju", "Mlečni izdelki", ["Ljubljanske mlekarne", "Meggle"], 2.29, "250 g"],
  ["Smetana za kuhanje", "Mlečni izdelki", ["Ljubljanske mlekarne", "Meggle"], 1.19, "200 ml"],
  ["Mascarpone", "Mlečni izdelki", ["Galbani", "Lidl"], 2.29, "250 g"],
  ["Ricotta", "Mlečni izdelki", ["Galbani"], 1.79, "250 g"],
  ["Zrnati sir (cottage)", "Mlečni izdelki", ["Ljubljanske mlekarne"], 1.49, "200 g"],
  ["Sir Tolminc", "Mlečni izdelki", ["Planika"], 3.99, "250 g"],
  ["Sir Mohant", "Mlečni izdelki", ["Planika"], 3.49, "200 g"],
  ["Sir Nanos", "Mlečni izdelki", ["Ljubljanske mlekarne"], 3.49, "250 g"],
  ["Sir Ementalec", "Mlečni izdelki", ["Ljubljanske mlekarne", "Pomurske mlekarne"], 2.79, "200 g"],
  ["Sir v lističih", "Mlečni izdelki", ["Ljubljanske mlekarne", "Milbona"], 1.79, "150 g"],
  ["Nariban sir", "Mlečni izdelki", ["Ljubljanske mlekarne", "Milbona"], 1.99, "200 g"],
  ["Sir Grana Padano", "Mlečni izdelki", ["Lidl", "Spar"], 3.99, "200 g"],
  ["Sir Brie", "Mlečni izdelki", ["Président", "Milbona"], 2.49, "125 g"],
  ["Sir Camembert", "Mlečni izdelki", ["Président", "Milbona"], 1.99, "125 g"],
  ["Sir Gorgonzola", "Mlečni izdelki", ["Galbani"], 2.49, "150 g"],
  ["Sir Halloumi", "Mlečni izdelki", ["Lidl", "Spar"], 2.99, "200 g"],
  ["Dimljeni sir", "Mlečni izdelki", ["Ljubljanske mlekarne", "Zbregov"], 2.29, "150 g"],
  ["Burata", "Mlečni izdelki", ["Lidl", "Spar"], 2.49, "125 g"],
  ["Margarina", "Mlečni izdelki", ["Rama", "Becel"], 1.89, "250 g"],
  ["Kremni sir", "Mlečni izdelki", ["Philadelphia"], 1.99, "175 g"],

  // Meso in ribe
  ["Piščančje perutničke", "Meso in ribe", ["Perutnina Ptuj", "Pivka"], 4.49, "kg"],
  ["Piščančji zrezki v ovojnici", "Meso in ribe", ["Perutnina Ptuj"], 3.99, "400 g"],
  ["Puranje prsi narezek", "Meso in ribe", ["Perutnina Ptuj", "Pivka"], 1.99, "100 g"],
  ["Piščančje hrenovke", "Meso in ribe", ["Perutnina Ptuj", "Pivka"], 1.99, "300 g"],
  ["Svinjska ribica", "Meso in ribe", [], 10.99, "kg"],
  ["Svinjska vratovina", "Meso in ribe", [], 7.99, "kg"],
  ["Svinjska rebrca", "Meso in ribe", [], 7.49, "kg"],
  ["Goveje meso za juho", "Meso in ribe", [], 9.99, "kg"],
  ["Goveji golaž", "Meso in ribe", [], 12.99, "kg"],
  ["Telečji zrezki", "Meso in ribe", [], 22.99, "kg"],
  ["Jagnjetina", "Meso in ribe", [], 16.99, "kg"],
  ["Čevapčiči", "Meso in ribe", ["Perutnina Ptuj", "Lidl"], 3.99, "400 g"],
  ["Pleskavice", "Meso in ribe", ["Perutnina Ptuj"], 3.99, "400 g"],
  ["Pečenice", "Meso in ribe", ["Celjske mesnine", "Mesnine dežele Kranjske"], 3.49, "400 g"],
  ["Krvavice", "Meso in ribe", ["Celjske mesnine"], 3.49, "400 g"],
  ["Mortadela", "Meso in ribe", ["Celjske mesnine", "Kras"], 1.29, "100 g"],
  ["Poli salama", "Meso in ribe", ["Perutnina Ptuj"], 1.49, "100 g"],
  ["Zimska salama", "Meso in ribe", ["Celjske mesnine", "Kras"], 2.49, "100 g"],
  ["Čajna klobasa", "Meso in ribe", ["Kras", "Celjske mesnine"], 2.49, "100 g"],
  ["Kraška panceta", "Meso in ribe", ["Kras"], 2.49, "100 g"],
  ["Suha šunka", "Meso in ribe", ["Kras", "Celjske mesnine"], 2.29, "100 g"],
  ["Prekajena šunka", "Meso in ribe", ["Celjske mesnine", "Mesnine dežele Kranjske"], 1.79, "100 g"],
  ["Ocvirki", "Meso in ribe", ["Celjske mesnine"], 2.99, "200 g"],
  ["Mast", "Meso in ribe", ["Celjske mesnine"], 1.99, "500 g"],
  ["Dimljeni losos", "Meso in ribe", ["Lidl", "Spar"], 3.49, "100 g"],
  ["Postrv", "Meso in ribe", ["Ribogojnica Faronika"], 13.99, "kg"],
  ["Orada", "Meso in ribe", [], 13.99, "kg"],
  ["Brancin", "Meso in ribe", [], 14.99, "kg"],
  ["Oslič file", "Meso in ribe", ["Lidl", "Iglo"], 4.99, "400 g"],
  ["Skuše v pločevinki", "Meso in ribe", ["Eva", "Lidl"], 1.69, "125 g"],
  ["Inćuni", "Meso in ribe", ["Eva"], 2.49, "50 g"],
  ["Kozice", "Meso in ribe", ["Lidl", "Spar"], 4.99, "200 g"],
  ["Lignji", "Meso in ribe", [], 12.99, "kg"],
  ["Školjke (dagnje)", "Meso in ribe", [], 5.99, "kg"],
  ["Tofu", "Meso in ribe", ["Taifun", "Vemondo"], 2.49, "200 g"],
  ["Rastlinski burger", "Meso in ribe", ["Vemondo", "Beyond Meat"], 2.99, "2 kos"],

  // Shramba – začimbe
  ["Sladka paprika", "Shramba", ["Kotányi", "Mercator"], 1.29, "100 g"],
  ["Pekoča paprika", "Shramba", ["Kotányi"], 1.49, "100 g"],
  ["Dimljena paprika", "Shramba", ["Kotányi"], 2.29, "70 g"],
  ["Poper v zrnju", "Shramba", ["Kotányi", "Mercator"], 2.49, "50 g"],
  ["Lovorjev list", "Shramba", ["Kotányi"], 1.19, "10 g"],
  ["Majaron", "Shramba", ["Kotányi"], 1.29, "10 g"],
  ["Kumina", "Shramba", ["Kotányi"], 1.49, "35 g"],
  ["Kurkuma", "Shramba", ["Kotányi"], 1.69, "35 g"],
  ["Muškatni orešček", "Shramba", ["Kotányi"], 2.29, "20 g"],
  ["Klinčki", "Shramba", ["Kotányi"], 1.99, "20 g"],
  ["Čili v prahu", "Shramba", ["Kotányi"], 1.49, "35 g"],
  ["Česen v prahu", "Shramba", ["Kotányi"], 1.49, "50 g"],
  ["Ingver v prahu", "Shramba", ["Kotányi"], 1.69, "25 g"],
  ["Bazilika suha", "Shramba", ["Kotányi"], 1.29, "10 g"],
  ["Timijan suh", "Shramba", ["Kotányi"], 1.29, "10 g"],
  ["Rožmarin suh", "Shramba", ["Kotányi"], 1.29, "20 g"],
  ["Peteršilj suh", "Shramba", ["Kotányi"], 1.29, "10 g"],
  ["Mlet koriander", "Shramba", ["Kotányi"], 1.49, "25 g"],
  ["Garam masala", "Shramba", ["Kotányi"], 1.99, "35 g"],
  ["Začimba za piščanca", "Shramba", ["Kotányi", "Podravka"], 1.29, "40 g"],
  ["Začimba za žar", "Shramba", ["Kotányi"], 1.29, "40 g"],
  ["Začimba za krompir", "Shramba", ["Kotányi"], 1.29, "40 g"],
  ["Morska sol", "Shramba", ["Piranske soline", "Solnce"], 1.99, "500 g"],
  ["Piranski solni cvet", "Shramba", ["Piranske soline"], 4.99, "100 g"],
  ["Vanilijev strok", "Shramba", ["Kotányi"], 2.99, "1 kos"],

  // Shramba – omake, konzerve, peka
  ["Paradižnikova omaka (pasata)", "Shramba", ["Mutti", "Podravka"], 1.49, "500 g"],
  ["Bolonjska omaka", "Shramba", ["Barilla", "Podravka"], 2.49, "400 g"],
  ["Pesto rosso", "Shramba", ["Barilla", "Lidl"], 2.49, "190 g"],
  ["Tatarska omaka", "Shramba", ["Thomy", "Mercator"], 1.49, "250 g"],
  ["Omaka BBQ", "Shramba", ["Heinz", "Kühne"], 2.49, "250 ml"],
  ["Sweet chili omaka", "Shramba", ["Blue Dragon", "Lidl"], 2.29, "200 ml"],
  ["Tabasco", "Shramba", ["Tabasco"], 3.49, "60 ml"],
  ["Hren v kozarcu", "Shramba", ["Podravka", "Ekoren"], 1.49, "190 g"],
  ["Worcester omaka", "Shramba", ["Lea & Perrins"], 2.99, "150 ml"],
  ["Paradižnik sušen", "Shramba", ["Lidl", "Spar"], 2.49, "280 g"],
  ["Kapre", "Shramba", ["Lidl"], 1.99, "100 g"],
  ["Pečena paprika v kozarcu", "Shramba", ["Podravka"], 1.99, "350 g"],
  ["Džuveč", "Shramba", ["Podravka"], 1.99, "680 g"],
  ["Rdeča pesa v kozarcu", "Shramba", ["Podravka", "Ekoren"], 1.29, "680 g"],
  ["Grah v pločevinki", "Shramba", ["Bonduelle", "Podravka"], 1.19, "400 g"],
  ["Rdeči fižol v pločevinki", "Shramba", ["Bonduelle", "Lidl"], 1.09, "400 g"],
  ["Fižol suh", "Shramba", ["Mercator", "Tuš"], 2.49, "500 g"],
  ["Ješprenj", "Shramba", ["Mlinotest", "Mercator"], 1.29, "500 g"],
  ["Ajdova kaša", "Shramba", ["Mlinotest", "Ekoren"], 2.49, "500 g"],
  ["Prosena kaša", "Shramba", ["Mlinotest"], 2.29, "500 g"],
  ["Kus kus", "Shramba", ["Lidl", "Spar"], 1.49, "500 g"],
  ["Bulgur", "Shramba", ["Lidl"], 1.69, "500 g"],
  ["Kvinoja", "Shramba", ["Lidl", "Spar"], 3.49, "400 g"],
  ["Riž za rižoto", "Shramba", ["Scotti", "Mercator"], 2.49, "1 kg"],
  ["Testenine fusilli", "Shramba", ["Barilla", "Mlinotest", "Combino"], 1.29, "500 g"],
  ["Testenine tagliatelle", "Shramba", ["Barilla", "Mlinotest"], 1.99, "500 g"],
  ["Jajčne testenine (rezanci)", "Shramba", ["Mlinotest", "Zlato polje"], 1.49, "500 g"],
  ["Jušne zvezdice", "Shramba", ["Mlinotest", "Zlato polje"], 0.99, "250 g"],
  ["Kitajski rezanci", "Shramba", ["Blue Dragon", "Lidl"], 1.79, "250 g"],
  ["Instant rezanci", "Shramba", ["Maggi", "Nissin"], 0.79, "kos"],
  ["Ajdova moka", "Shramba", ["Mlinotest", "Ekoren"], 2.29, "1 kg"],
  ["Pirina moka", "Shramba", ["Mlinotest", "Ekoren"], 2.49, "1 kg"],
  ["Ostra moka", "Shramba", ["Mlinotest", "Žito"], 1.19, "1 kg"],
  ["Pšenični zdrob", "Shramba", ["Mlinotest"], 1.19, "500 g"],
  ["Koruzni škrob", "Shramba", ["Gustin", "Dr. Oetker"], 1.29, "200 g"],
  ["Sladkor v prahu", "Shramba", ["Viljem Julijan", "Mercator"], 1.19, "500 g"],
  ["Rjavi sladkor", "Shramba", ["Viljem Julijan", "Lidl"], 1.99, "500 g"],
  ["Želatina", "Shramba", ["Dr. Oetker"], 0.99, "20 g"],
  ["Soda bikarbona", "Shramba", ["Dr. Oetker", "Kotányi"], 0.49, "50 g"],
  ["Mandlji mleti", "Shramba", ["Lidl", "Spar"], 2.99, "200 g"],
  ["Orehi", "Shramba", ["Lidl", "Mercator"], 3.49, "200 g"],
  ["Lešniki mleti", "Shramba", ["Lidl", "Mercator"], 2.99, "200 g"],
  ["Kokosova moka", "Shramba", ["Lidl", "Mercator"], 1.29, "200 g"],
  ["Mak", "Shramba", ["Mercator", "Lidl"], 1.99, "200 g"],
  ["Čokoladne kapljice", "Shramba", ["Dr. Oetker", "Lidl"], 1.99, "100 g"],
  ["Posip za torte", "Shramba", ["Dr. Oetker"], 1.29, "80 g"],
  ["Preliv za torte", "Shramba", ["Dr. Oetker"], 0.79, "kos"],
  ["Jedilna barva", "Shramba", ["Dr. Oetker"], 1.99, "kos"],
  ["Mešanica za palačinke", "Shramba", ["Dr. Oetker", "Podravka"], 1.99, "kos"],
  ["Puding v prahu", "Shramba", ["Dr. Oetker", "Podravka"], 0.49, "kos"],
  ["Javorjev sirup", "Shramba", ["Lidl", "Spar"], 4.99, "250 ml"],
  ["Agavin sirup", "Shramba", ["Lidl"], 2.99, "250 ml"],
  ["Ksilitol", "Shramba", ["Lidl"], 4.99, "500 g"],
  ["Sladilo", "Shramba", ["Natreen", "Canderel"], 2.49, "kos"],
  ["Slivov pekmez", "Shramba", ["Podravka"], 2.49, "450 g"],
  ["Kompot breskve", "Shramba", ["Podravka", "Lidl"], 1.99, "820 g"],
  ["Ananas v pločevinki", "Shramba", ["Del Monte", "Lidl"], 1.69, "565 g"],
  ["Repično olje", "Shramba", ["Lidl", "Mercator"], 2.49, "1 l"],
  ["Bučno olje", "Shramba", ["Oljarna Kocbek", "Pomurka"], 9.99, "0,5 l"],
  ["Kokosova maščoba", "Shramba", ["Lidl"], 2.99, "500 ml"],
  ["Jabolčni kis", "Shramba", ["Mercator", "Lidl"], 0.99, "1 l"],
  ["Limonin sok (koncentrat)", "Shramba", ["Mercator"], 0.99, "0,5 l"],
  ["Govedska juha v kocki", "Shramba", ["Knorr", "Podravka"], 1.29, "kos"],
  ["Fond za omake", "Shramba", ["Knorr", "Podravka"], 1.49, "kos"],
  ["Pire krompir v prahu", "Shramba", ["Knorr", "Podravka"], 1.49, "kos"],
  ["Hummus", "Shramba", ["Lidl", "Spar"], 1.79, "200 g"],

  // Prigrizki
  ["Tortilja čips", "Prigrizki", ["Chio", "Doritos"], 1.99, "125 g"],
  ["Flips", "Prigrizki", ["Smoki", "Chio"], 1.29, "100 g"],
  ["Pokovka", "Prigrizki", ["Lidl", "Spar"], 1.49, "3 kos"],
  ["Slani krekerji", "Prigrizki", ["TUC", "Ritz"], 1.29, "100 g"],
  ["Pistacije", "Prigrizki", ["Lidl", "Spar"], 3.99, "150 g"],
  ["Indijski oreščki", "Prigrizki", ["Lidl", "Spar"], 2.99, "200 g"],
  ["Mandlji", "Prigrizki", ["Lidl", "Spar"], 2.99, "200 g"],
  ["Lešniki", "Prigrizki", ["Lidl", "Spar"], 2.99, "200 g"],
  ["Študentska hrana", "Prigrizki", ["Lidl", "Mercator"], 2.49, "200 g"],
  ["Bučna semena", "Prigrizki", ["Lidl", "Mercator"], 2.49, "200 g"],
  ["Sončnična semena", "Prigrizki", ["Lidl", "Mercator"], 1.49, "200 g"],
  ["Gorenjka lešnik", "Prigrizki", ["Gorenjka"], 2.49, "220 g"],
  ["Kinder čokolada", "Prigrizki", ["Kinder"], 2.49, "100 g"],
  ["Kinder jajček", "Prigrizki", ["Kinder"], 1.39, "kos"],
  ["Bombonjera", "Prigrizki", ["Ferrero Rocher", "Merci", "Raffaello"], 6.99, "200 g"],
  ["Čokoladne ploščice", "Prigrizki", ["Snickers", "Mars", "Twix", "Bounty"], 1.19, "kos"],
  ["Kit Kat", "Prigrizki", ["Nestlé"], 0.99, "kos"],
  ["Gumijasti bonboni", "Prigrizki", ["Haribo"], 1.49, "100 g"],
  ["Žvečilni gumi", "Prigrizki", ["Orbit", "Airwaves", "Mentos"], 1.39, "kos"],
  ["Lizike", "Prigrizki", ["Chupa Chups"], 0.29, "kos"],
  ["Bajadera", "Prigrizki", ["Kraš"], 4.99, "225 g"],
  ["Jaffa piškoti", "Prigrizki", ["Kraš"], 1.69, "150 g"],
  ["Petit beurre", "Prigrizki", ["Žito", "Kraš"], 0.99, "200 g"],
  ["Polnozrnati piškoti", "Prigrizki", ["Belvita", "Žito"], 1.99, "300 g"],
  ["Masleni piškoti", "Prigrizki", ["Leibniz", "Lidl"], 1.69, "200 g"],
  ["Čajno pecivo", "Prigrizki", ["Žito", "Mercator"], 2.49, "400 g"],
  ["Oreo piškoti", "Prigrizki", ["Oreo"], 1.69, "154 g"],
  ["Medenjaki", "Prigrizki", ["Žito", "Lidl"], 1.99, "300 g"],
  ["Riževi vafli s čokolado", "Prigrizki", ["Lidl", "Spar"], 1.49, "100 g"],
  ["Müsli ploščica", "Prigrizki", ["Corny", "Lidl"], 0.59, "kos"],
  ["Mafini", "Prigrizki", ["Lidl", "Spar"], 2.49, "kos"],

  // Pijače
  ["Donat Mg", "Pijače", ["Donat"], 2.29, "1 l"],
  ["Aromatizirana voda", "Pijače", ["Radenska", "Zala", "Jana"], 1.19, "1,5 l"],
  ["Sok multivitamin", "Pijače", ["Fructal", "Happy Day"], 1.99, "1 l"],
  ["Sok ananas", "Pijače", ["Fructal", "Happy Day"], 1.99, "1 l"],
  ["Sok grenivka", "Pijače", ["Fructal", "Happy Day"], 2.19, "1 l"],
  ["Sok borovnica", "Pijače", ["Fructal"], 2.29, "1 l"],
  ["Sok paradižnik", "Pijače", ["Fructal", "Happy Day"], 1.99, "1 l"],
  ["Sveže stisnjen pomarančni sok", "Pijače", ["Lidl", "Spar"], 3.49, "1 l"],
  ["Smoothie", "Pijače", ["Innocent", "Fructal"], 2.49, "250 ml"],
  ["Jupi", "Pijače", ["Fructal"], 1.49, "1,5 l"],
  ["Pepsi", "Pijače", ["Pepsi"], 1.69, "1,5 l"],
  ["Schweppes tonik", "Pijače", ["Schweppes"], 1.79, "1,5 l"],
  ["Schweppes bitter lemon", "Pijače", ["Schweppes"], 1.79, "1,5 l"],
  ["Izotonični napitek", "Pijače", ["Isostar", "Powerade"], 1.79, "500 ml"],
  ["Kava brez kofeina", "Pijače", ["Barcaffe", "Jacobs"], 5.49, "250 g"],
  ["Barcaffe 3v1", "Pijače", ["Barcaffe"], 2.99, "10 kos"],
  ["Ledena kava", "Pijače", ["Barcaffe", "Starbucks"], 1.69, "220 ml"],
  ["Zeleni čaj", "Pijače", ["Teekanne", "1001 cvet", "Lipton"], 2.29, "20 vrečk"],
  ["Kamilični čaj", "Pijače", ["1001 cvet", "Teekanne"], 1.99, "20 vrečk"],
  ["Metin čaj", "Pijače", ["1001 cvet", "Teekanne"], 1.99, "20 vrečk"],
  ["Sadni čaj", "Pijače", ["Teekanne", "1001 cvet"], 2.19, "20 vrečk"],
  ["Šipkov čaj", "Pijače", ["1001 cvet"], 1.99, "20 vrečk"],
  ["Črni čaj", "Pijače", ["Lipton", "Teekanne"], 2.49, "25 vrečk"],
  ["Kakav napitek", "Pijače", ["Benquick", "Nesquik"], 3.49, "400 g"],
  ["Brezalkoholno pivo", "Pijače", ["Laško", "Union", "Heineken"], 1.09, "0,5 l"],
  ["Temno pivo", "Pijače", ["Union", "Laško"], 1.39, "0,5 l"],
  ["Pšenično pivo", "Pijače", ["Paulaner", "Erdinger"], 1.79, "0,5 l"],
  ["Craft pivo", "Pijače", ["Pelicon", "Human Fish", "Reservoir Dogs"], 3.49, "0,33 l"],
  ["Rose vino", "Pijače", ["Vinakoper", "Goriška Brda"], 5.99, "0,75 l"],
  ["Cviček", "Pijače", ["KZ Krško"], 4.49, "1 l"],
  ["Teran", "Pijače", ["Vinakras"], 7.99, "0,75 l"],
  ["Refošk", "Pijače", ["Vinakoper"], 6.49, "0,75 l"],
  ["Malvazija", "Pijače", ["Vinakoper"], 6.49, "0,75 l"],
  ["Rebula", "Pijače", ["Goriška Brda"], 7.49, "0,75 l"],
  ["Laški rizling", "Pijače", ["Puklavec", "Ptujska klet"], 5.49, "0,75 l"],
  ["Prosecco", "Pijače", ["Martini", "Lidl"], 7.99, "0,75 l"],
  ["Šampanjec", "Pijače", ["Moët & Chandon"], 49.99, "0,75 l"],
  ["Vodka", "Pijače", ["Smirnoff", "Absolut", "Finlandia"], 14.99, "0,7 l"],
  ["Gin", "Pijače", ["Gordon's", "Bombay Sapphire", "Beefeater"], 19.99, "0,7 l"],
  ["Rum", "Pijače", ["Bacardi", "Captain Morgan"], 16.99, "0,7 l"],
  ["Viski", "Pijače", ["Jameson", "Johnnie Walker", "Jack Daniel's"], 22.99, "0,7 l"],
  ["Jägermeister", "Pijače", ["Jägermeister"], 17.99, "0,7 l"],
  ["Pelinkovec", "Pijače", ["Badel"], 11.99, "0,7 l"],
  ["Slivovka", "Pijače", ["Dana"], 14.99, "0,7 l"],
  ["Viljamovka", "Pijače", ["Dana"], 16.99, "0,7 l"],
  ["Borovničevec", "Pijače", ["Dana"], 12.99, "0,7 l"],
  ["Aperol", "Pijače", ["Aperol"], 15.99, "0,7 l"],
  ["Martini vermut", "Pijače", ["Martini"], 10.99, "1 l"],
  ["Liker Baileys", "Pijače", ["Baileys"], 17.99, "0,7 l"],

  // Zamrznjeno
  ["Zamrznjena špinača", "Zamrznjeno", ["Iglo", "Ledo"], 1.99, "450 g"],
  ["Zamrznjeni brokoli", "Zamrznjeno", ["Iglo", "Ledo"], 1.99, "450 g"],
  ["Zamrznjena mešanica za juho", "Zamrznjeno", ["Ledo", "Mercator"], 1.79, "400 g"],
  ["Zamrznjeno sadje", "Zamrznjeno", ["Ledo", "Lidl"], 2.99, "500 g"],
  ["Zamrznjene jagode", "Zamrznjeno", ["Ledo", "Lidl"], 2.79, "500 g"],
  ["Krompirjeve kroglice", "Zamrznjeno", ["McCain"], 2.49, "450 g"],
  ["Krompirjevi svaljki (rösti)", "Zamrznjeno", ["McCain", "Lidl"], 2.29, "400 g"],
  ["Zamrznjene kozice", "Zamrznjeno", ["Lidl", "Ledo"], 6.99, "400 g"],
  ["Zamrznjeni lignji", "Zamrznjeno", ["Ledo", "Lidl"], 5.99, "500 g"],
  ["Zamrznjeni file postrvi", "Zamrznjeno", ["Lidl"], 5.49, "400 g"],
  ["Piščančji nuggetsi", "Zamrznjeno", ["Perutnina Ptuj", "Lidl"], 3.99, "500 g"],
  ["Lazanja zamrznjena", "Zamrznjeno", ["Lidl", "Spar"], 3.49, "400 g"],
  ["Burek zamrznjen", "Zamrznjeno", ["Pekarna Pečjak", "Mercator"], 3.99, "1 kg"],
  ["Cmoki s slivami", "Zamrznjeno", ["Pekarna Pečjak", "Ledo"], 3.49, "600 g"],
  ["Marelični cmoki", "Zamrznjeno", ["Ledo", "Pekarna Pečjak"], 3.49, "600 g"],
  ["Zamrznjeni štruklji", "Zamrznjeno", ["Pekarna Pečjak"], 3.49, "500 g"],
  ["Tortelini", "Zamrznjeno", ["Rana", "Lidl"], 2.99, "250 g"],
  ["Zamrznjeni rogljički", "Zamrznjeno", ["Pekarna Pečjak", "Lidl"], 2.99, "10 kos"],
  ["Lučka sladoled", "Zamrznjeno", ["Ledo"], 1.29, "kos"],
  ["Sladoled na palčki", "Zamrznjeno", ["Magnum", "Ledo"], 1.79, "kos"],
  ["Sladoled v kornetu", "Zamrznjeno", ["Cornetto", "Ledo"], 1.49, "kos"],
  ["Sladoledna torta", "Zamrznjeno", ["Ledo"], 5.99, "kos"],
  ["Led v kockah", "Zamrznjeno", [], 1.49, "2 kg"],

  // Gospodinjstvo
  ["Gel kapsule za pranje", "Gospodinjstvo", ["Ariel", "Persil"], 13.99, "kos"],
  ["Detergent za občutljivo perilo", "Gospodinjstvo", ["Perwoll", "Bio Plus"], 6.99, "kos"],
  ["Odstranjevalec madežev", "Gospodinjstvo", ["Vanish"], 6.49, "kos"],
  ["Lovilci barv", "Gospodinjstvo", ["Color Catcher", "Lidl"], 3.49, "kos"],
  ["Sol za pomivalni stroj", "Gospodinjstvo", ["Finish", "Somat"], 1.99, "1,5 kg"],
  ["Sijaj za pomivalni stroj", "Gospodinjstvo", ["Finish", "Somat"], 3.49, "400 ml"],
  ["Čistilo za stroj", "Gospodinjstvo", ["Finish", "Calgon"], 4.99, "kos"],
  ["Čistilo za tla", "Gospodinjstvo", ["Mr. Proper", "Ajax"], 2.99, "1 l"],
  ["Čistilo za steklo", "Gospodinjstvo", ["Clin", "Ajax"], 2.49, "500 ml"],
  ["Univerzalno čistilo", "Gospodinjstvo", ["Ajax", "Mr. Proper", "Cif"], 2.49, "1 l"],
  ["Čistilo za kuhinjo", "Gospodinjstvo", ["Cif", "Mr. Muscle"], 2.99, "500 ml"],
  ["Odstranjevalec vodnega kamna", "Gospodinjstvo", ["Viakal", "Cillit Bang"], 3.99, "500 ml"],
  ["Čistilo za WC", "Gospodinjstvo", ["Domestos", "WC Duck"], 2.49, "750 ml"],
  ["WC osvežilec", "Gospodinjstvo", ["Bref", "Domestos"], 2.29, "kos"],
  ["Varikina", "Gospodinjstvo", ["Varikina", "Domestos"], 1.29, "1 l"],
  ["Čistilo za odtoke", "Gospodinjstvo", ["Mr. Muscle", "Krtek"], 3.99, "kos"],
  ["Osvežilec zraka", "Gospodinjstvo", ["Air Wick", "Glade"], 3.49, "kos"],
  ["Krpe za čiščenje", "Gospodinjstvo", ["Vileda", "Spontex"], 2.99, "3 kos"],
  ["Mikrovlaknasta krpa", "Gospodinjstvo", ["Vileda"], 2.49, "kos"],
  ["Gumijaste rokavice", "Gospodinjstvo", ["Vileda", "Spontex"], 1.99, "par"],
  ["Papirnati prtički", "Gospodinjstvo", ["Paloma", "Tento"], 1.49, "kos"],
  ["Prozorna folija", "Gospodinjstvo", ["Toppits", "Albal"], 1.99, "30 m"],
  ["Papir za peko", "Gospodinjstvo", ["Toppits", "Albal"], 1.99, "kos"],
  ["Vrečke za zamrzovanje", "Gospodinjstvo", ["Toppits", "Albal"], 1.99, "kos"],
  ["Vrečke za sendviče", "Gospodinjstvo", ["Toppits"], 1.49, "kos"],
  ["Nakupovalna vrečka", "Gospodinjstvo", [], 0.29, "kos"],
  ["Vrečke za bio odpadke", "Gospodinjstvo", ["Lidl", "Mercator"], 2.49, "kos"],
  ["Žarnica LED", "Gospodinjstvo", ["Philips", "Osram"], 3.99, "kos"],
  ["Baterije AAA", "Gospodinjstvo", ["Duracell", "Energizer", "Varta"], 6.99, "4 kos"],
  ["Gumbna baterija", "Gospodinjstvo", ["Varta", "Duracell"], 3.49, "kos"],
  ["Sveče", "Gospodinjstvo", ["Lidl", "Mercator"], 2.99, "kos"],
  ["Nagrobna sveča", "Gospodinjstvo", [], 1.99, "kos"],
  ["Čajne svečke", "Gospodinjstvo", ["Lidl", "IKEA"], 1.99, "kos"],
  ["Prižigalnik za žar", "Gospodinjstvo", ["Lidl"], 1.99, "kos"],
  ["Oglje za žar", "Gospodinjstvo", ["Lidl", "Mercator"], 4.99, "3 kg"],
  ["Plastični kozarci", "Gospodinjstvo", [], 1.49, "kos"],
  ["Papirnati krožniki", "Gospodinjstvo", [], 1.99, "kos"],
  ["Lepilni trak", "Gospodinjstvo", ["Tesa", "Scotch"], 1.99, "kos"],
  ["Sprej proti komarjem", "Gospodinjstvo", ["Autan", "Off!"], 6.99, "kos"],
  ["Sredstvo proti mrčesu", "Gospodinjstvo", ["Raid", "Baygon"], 5.99, "kos"],
  ["Krema za čevlje", "Gospodinjstvo", ["Kiwi", "Erdal"], 2.99, "kos"],

  // Higiena
  ["Ustna voda", "Higiena", ["Listerine", "Colgate"], 4.49, "500 ml"],
  ["Zobna nitka", "Higiena", ["Oral-B"], 2.99, "kos"],
  ["Medzobne ščetke", "Higiena", ["Curaprox", "TePe"], 4.99, "kos"],
  ["Glave za električno ščetko", "Higiena", ["Oral-B", "Philips Sonicare"], 14.99, "kos"],
  ["Balzam za lase", "Higiena", ["Pantene", "Garnier", "Nivea"], 3.49, "kos"],
  ["Maska za lase", "Higiena", ["Garnier", "Gliss"], 4.99, "kos"],
  ["Lak za lase", "Higiena", ["Taft", "Elnett"], 3.99, "kos"],
  ["Gel za lase", "Higiena", ["Taft"], 2.99, "kos"],
  ["Barva za lase", "Higiena", ["Garnier", "Schwarzkopf", "L'Oréal"], 7.99, "kos"],
  ["Suhi šampon", "Higiena", ["Batiste"], 4.99, "kos"],
  ["Tekoče milo", "Higiena", ["Palmolive", "Dove"], 1.99, "kos"],
  ["Losjon za telo", "Higiena", ["Nivea", "Dove"], 4.99, "kos"],
  ["Krema za obraz", "Higiena", ["Nivea", "Garnier", "L'Oréal"], 6.99, "kos"],
  ["Micelarna voda", "Higiena", ["Garnier", "Balea"], 4.49, "400 ml"],
  ["Odstranjevalec ličil", "Higiena", ["Garnier", "Nivea"], 3.99, "kos"],
  ["Vatirane blazinice", "Higiena", ["Cottonino", "Balea"], 1.29, "kos"],
  ["Vatirane palčke", "Higiena", ["Johnson's", "Cottonino"], 0.99, "kos"],
  ["Balzam za ustnice", "Higiena", ["Labello", "Nivea"], 2.49, "kos"],
  ["Krema za sončenje", "Higiena", ["Nivea", "Garnier Ambre Solaire"], 11.99, "kos"],
  ["Krema po sončenju", "Higiena", ["Nivea"], 6.99, "kos"],
  ["Parfum", "Higiena", ["Hugo Boss", "Calvin Klein"], 39.99, "kos"],
  ["Gel za britje", "Higiena", ["Gillette", "Nivea"], 3.99, "kos"],
  ["Losjon po britju", "Higiena", ["Nivea", "Gillette"], 6.99, "kos"],
  ["Nadomestne britvice", "Higiena", ["Gillette", "Wilkinson"], 16.99, "kos"],
  ["Vosek trakovi", "Higiena", ["Veet"], 6.99, "kos"],
  ["Tamponi", "Higiena", ["o.b.", "Tampax"], 3.99, "kos"],
  ["Dnevni vložki", "Higiena", ["Carefree", "Always"], 2.49, "kos"],
  ["Menstrualne hlačke", "Higiena", ["Lidl", "Libresse"], 9.99, "kos"],
  ["Intimni gel", "Higiena", ["Lactacyd", "Intima"], 4.99, "kos"],
  ["Inkontinenčne predloge", "Higiena", ["Tena", "Seni"], 7.99, "kos"],
  ["Kondomi", "Higiena", ["Durex"], 9.99, "kos"],
  ["Vlažni toaletni papir", "Higiena", ["Paloma", "Cushelle"], 1.99, "kos"],
  ["Pilica za nohte", "Higiena", [], 1.49, "kos"],
  ["Lak za nohte", "Higiena", ["Essence", "Maybelline"], 2.99, "kos"],
  ["Odstranjevalec laka", "Higiena", ["Essence", "Balea"], 1.99, "kos"],
  ["Maskara", "Higiena", ["Maybelline", "Essence", "L'Oréal"], 8.99, "kos"],
  ["Puder", "Higiena", ["Maybelline", "Essence"], 6.99, "kos"],

  // Otroci
  ["Plenice hlačke", "Otroci", ["Pampers", "Huggies"], 13.99, "kos"],
  ["Začetno mleko", "Otroci", ["Aptamil", "Bebivita", "Nutrilon"], 19.99, "800 g"],
  ["Nadaljevalno mleko", "Otroci", ["Aptamil", "Bebivita", "Nutrilon"], 17.99, "800 g"],
  ["Otroška kašica", "Otroci", ["Hipp", "Bebivita", "Nestlé"], 3.49, "kos"],
  ["Otroški kozarček (sadje)", "Otroci", ["Hipp", "Bebivita"], 1.29, "190 g"],
  ["Otroški kozarček (meni)", "Otroci", ["Hipp", "Bebivita"], 1.79, "220 g"],
  ["Sadna stiskalka", "Otroci", ["Hipp", "Bebivita", "Fructal"], 0.99, "90 g"],
  ["Otroški piškoti", "Otroci", ["Hipp", "Plasmon"], 2.49, "kos"],
  ["Otroški čaj", "Otroci", ["Hipp"], 2.99, "kos"],
  ["Krema za ritko", "Otroci", ["Sudocrem", "Bepanthen", "Penaten"], 6.99, "kos"],
  ["Otroški šampon", "Otroci", ["Johnson's", "Bübchen"], 3.49, "kos"],
  ["Otroško olje", "Otroci", ["Johnson's"], 3.99, "kos"],
  ["Duda", "Otroci", ["NUK", "Avent"], 6.99, "kos"],
  ["Otroška steklenička", "Otroci", ["NUK", "Avent"], 9.99, "kos"],
  ["Previjalne podloge", "Otroci", ["Lupilu", "Pampers"], 4.99, "kos"],
  // Dojenčki (nega, prehrana, oprema – tudi Baby Center)
  ["Plenice za novorojenčke", "Otroci", ["Pampers Premium Care", "Huggies", "Libero", "Babylove"], 9.99, "kos"],
  ["Nočne hlačke", "Otroci", ["Pampers Ninjamas", "Huggies DryNites"], 9.99, "kos"],
  ["Plenice za plavanje", "Otroci", ["Huggies Little Swimmers", "Libero Swimpants"], 7.99, "kos"],
  ["Pralne plenice", "Otroci", ["Bambino Mio", "Close"], 15.99, "kos"],
  ["Tetra pleničke", "Otroci", ["Babylove", "Lupilu"], 9.99, "kos"],
  ["Vlažilni robčki za dojenčke", "Otroci", ["WaterWipes", "Pampers Sensitive", "Huggies", "Babylove"], 2.49, "kos"],
  ["Vrečke za plenice", "Otroci", ["Babylove", "Sangenic"], 2.99, "kos"],
  ["Gel za kopanje dojenčkov", "Otroci", ["Bübchen", "Johnson's", "Babylove", "Penaten"], 3.99, "kos"],
  ["Otroški losjon", "Otroci", ["Johnson's", "Bübchen", "Weleda"], 4.49, "kos"],
  ["Otroška krema za obraz", "Otroci", ["Bübchen", "Weleda", "Penaten"], 4.99, "kos"],
  ["Otroški puder", "Otroci", ["Johnson's", "Penaten"], 3.49, "kos"],
  ["Otroška sončna krema", "Otroci", ["Nivea Kids", "Bübchen", "Garnier Kids"], 9.99, "kos"],
  ["Otroška zobna pasta", "Otroci", ["Elmex", "Signal Kids", "Nenedent"], 2.99, "kos"],
  ["Otroška zobna ščetka", "Otroci", ["Elmex", "NUK", "Curaprox"], 2.99, "kos"],
  ["Vatirane palčke za dojenčke", "Otroci", ["Johnson's", "Babylove"], 1.99, "kos"],
  ["Detergent za otroško perilo", "Otroci", ["Persil Sensitive", "Ariel Sensitive", "Babylove"], 9.99, "kos"],
  ["Morska voda za nosek", "Otroci", ["Physiomer", "Sterimar", "Quixx"], 7.99, "kos"],
  ["Aspirator za nosek", "Otroci", ["NUK", "Nosko", "Chicco"], 8.99, "kos"],
  ["Termometer za dojenčke", "Otroci", ["Braun", "Chicco"], 19.99, "kos"],
  ["Gel za dlesni", "Otroci", ["Dentinox", "Calgel"], 6.99, "kos"],
  ["Kapljice proti kolikam", "Otroci", ["Espumisan", "Sab Simplex", "BioGaia"], 8.99, "kos"],
  ["Vitamin D kapljice", "Otroci", ["Plivit D3", "Devit", "BioGaia"], 7.99, "kos"],
  ["Blazinice za dojenje", "Otroci", ["Lansinoh", "NUK", "Medela"], 6.99, "kos"],
  ["Krema za bradavice", "Otroci", ["Lansinoh", "Medela Purelan"], 9.99, "kos"],
  ["Vrečke za materino mleko", "Otroci", ["Lansinoh", "Medela", "NUK"], 9.99, "kos"],
  ["Prsna črpalka", "Otroci", ["Medela", "Philips Avent", "Lansinoh"], 59.99, "kos"],
  ["Mleko za malčke", "Otroci", ["Aptamil", "Bebivita", "Nutrilon"], 15.99, "800 g"],
  ["Hipoalergeno mleko", "Otroci", ["Aptamil HA", "Nutrilon HA", "Hipp HA"], 22.99, "800 g"],
  ["Mlečna kašica", "Otroci", ["Hipp", "Bebivita", "Nestlé"], 3.99, "kos"],
  ["Riževa kašica", "Otroci", ["Hipp", "Bebivita", "Holle"], 3.49, "kos"],
  ["Otroška voda", "Otroci", ["Hipp", "Bebivita"], 1.29, "1 l"],
  ["Otroški sok", "Otroci", ["Hipp", "Bebivita"], 1.49, "kos"],
  ["Otroški riževi krekerji", "Otroci", ["Hipp", "Bebivita", "Holle"], 1.99, "kos"],
  ["Otroške testenine", "Otroci", ["Hipp", "Bebivita"], 1.99, "kos"],
  ["Cuclji za stekleničko", "Otroci", ["NUK", "Philips Avent", "MAM"], 6.99, "kos"],
  ["Verižica za dudo", "Otroci", ["NUK", "MAM", "Philips Avent"], 5.99, "kos"],
  ["Grizalo", "Otroci", ["NUK", "MAM", "Chicco"], 6.99, "kos"],
  ["Lonček za učenje pitja", "Otroci", ["NUK", "MAM", "Philips Avent"], 9.99, "kos"],
  ["Otroški jedilni pribor", "Otroci", ["NUK", "Chicco", "Tommee Tippee"], 7.99, "kos"],
  ["Slinček", "Otroci", ["Babylove", "NUK"], 4.99, "kos"],
  ["Krtača za stekleničke", "Otroci", ["NUK", "Philips Avent"], 5.99, "kos"],
  ["Sterilizator stekleničk", "Otroci", ["Philips Avent", "NUK", "Chicco"], 49.99, "kos"],
  ["Grelnik stekleničk", "Otroci", ["Philips Avent", "NUK"], 34.99, "kos"],
  ["Dozirnik za mlečni prah", "Otroci", ["NUK", "Philips Avent"], 5.99, "kos"],
  ["Kahlica", "Otroci", ["Chicco", "OKBaby", "Brevi"], 9.99, "kos"],
  ["Nastavek za WC školjko", "Otroci", ["Chicco", "OKBaby"], 12.99, "kos"],
  ["Otroška kadička", "Otroci", ["OKBaby", "Chicco"], 19.99, "kos"],
  ["Bodiji za dojenčke", "Otroci", ["Lupilu", "Babylove"], 12.99, "komplet"],
  ["Spalna vreča za dojenčke", "Otroci", ["Lupilu", "Babylove"], 29.99, "kos"],
  ["Previjalna torba", "Otroci", ["Chicco", "Babymoov"], 39.99, "kos"],
  ["Varuška", "Otroci", ["Philips Avent", "Motorola"], 59.99, "kos"],
  ["Nosilka za dojenčka", "Otroci", ["Ergobaby", "BabyBjörn"], 99.99, "kos"],
  ["Avtosedež", "Otroci", ["Cybex", "Maxi-Cosi", "Britax Römer"], 199.99, "kos"],
  ["Otroški voziček", "Otroci", ["Cybex", "Bugaboo", "Chicco"], 499.99, "kos"],
  ["Varovala za vtičnice", "Otroci", ["Reer", "Chicco"], 4.99, "kos"],

  // Zdravje
  ["Obliži", "Zdravje", ["Hansaplast", "Lidl"], 2.99, "kos"],
  ["Elastični povoj", "Zdravje", ["Hartmann"], 2.49, "kos"],
  ["Gaza", "Zdravje", ["Hartmann"], 1.99, "kos"],
  ["Razkužilo za roke", "Zdravje", ["Sanytol", "Dettol"], 3.99, "kos"],
  ["Vitamin C", "Zdravje", ["Cedevita", "Krka", "Doppelherz"], 4.99, "kos"],
  ["Vitamin D", "Zdravje", ["Krka", "Doppelherz"], 6.99, "kos"],
  ["Magnezij", "Zdravje", ["Doppelherz", "Krka"], 5.99, "kos"],
  ["Multivitamini", "Zdravje", ["Centrum", "Doppelherz"], 9.99, "kos"],
  ["Šumeče tablete", "Zdravje", ["Cedevita", "Doppelherz"], 1.99, "kos"],
  ["Cink", "Zdravje", ["Doppelherz"], 5.99, "kos"],
  ["Ribje olje (omega-3)", "Zdravje", ["Doppelherz"], 8.99, "kos"],
  ["Bonboni za grlo", "Zdravje", ["Ricola", "Fisherman's Friend"], 2.49, "kos"],
  ["Pastile za grlo", "Zdravje", ["Krka", "Strepsils"], 6.99, "kos"],
  ["Sprej za nos (morska voda)", "Zdravje", ["Aqua Maris", "Physiomer"], 6.99, "kos"],
  ["Termometer", "Zdravje", ["Microlife"], 7.99, "kos"],
  ["Zaščitne maske", "Zdravje", [], 3.99, "kos"],
  ["Probiotik", "Zdravje", ["Linex", "Bio-Gaia"], 9.99, "kos"],
  ["Elektroliti", "Zdravje", ["Isostar", "Krka"], 3.99, "kos"],

  // Ljubljenčki
  ["Briketi za mačke", "Ljubljenčki", ["Whiskas", "Purina Cat Chow", "Coshida"], 4.99, "1,5 kg"],
  ["Briketi za pse", "Ljubljenčki", ["Pedigree", "Purina Dog Chow", "Orlando"], 7.99, "3 kg"],
  ["Pasje konzerve", "Ljubljenčki", ["Pedigree", "Chappi", "Orlando"], 1.49, "400 g"],
  ["Priboljški za pse", "Ljubljenčki", ["Pedigree Dentastix"], 2.99, "kos"],
  ["Priboljški za mačke", "Ljubljenčki", ["Whiskas Temptations", "Dreamies"], 1.99, "kos"],
  ["Hrana za ptice", "Ljubljenčki", ["Vitakraft", "Lidl"], 2.49, "1 kg"],
  ["Hrana za ribice", "Ljubljenčki", ["Tetra"], 3.99, "kos"],
  ["Hrana za glodavce", "Ljubljenčki", ["Vitakraft"], 3.49, "1 kg"],
  ["Vrečke za pasje iztrebke", "Ljubljenčki", [], 1.99, "kos"],
  ["Podloge za ljubljenčke", "Ljubljenčki", ["Lidl"], 4.99, "kos"],
  // Hrana in oprema za živali (tudi Mr. Pet, Premium Pet)
  ["Premium briketi za pse", "Ljubljenčki", ["Royal Canin", "Brit Care", "Josera", "Acana", "Purina Pro Plan"], 19.99, "3 kg"],
  ["Briketi za mladičke", "Ljubljenčki", ["Royal Canin Puppy", "Brit Care Puppy", "Josera"], 17.99, "3 kg"],
  ["Premium briketi za mačke", "Ljubljenčki", ["Royal Canin", "Hill's", "Purina Pro Plan", "Brit Care"], 16.99, "2 kg"],
  ["Hrana za mucke", "Ljubljenčki", ["Royal Canin Kitten", "Whiskas Junior", "Felix"], 6.99, "1,5 kg"],
  ["Dietna hrana za ljubljenčke", "Ljubljenčki", ["Royal Canin Veterinary", "Hill's Prescription Diet"], 24.99, "2 kg"],
  ["Mačje konzerve", "Ljubljenčki", ["Animonda", "Applaws", "Gourmet", "Schesir"], 1.29, "100 g"],
  ["Mleko za mačke", "Ljubljenčki", ["Whiskas", "GimCat"], 1.29, "200 ml"],
  ["Pasta za mačke", "Ljubljenčki", ["GimCat", "Beaphar"], 5.99, "kos"],
  ["Mačja trava", "Ljubljenčki", ["Vitakraft", "Trixie"], 2.49, "kos"],
  ["Silikonski pesek za mačke", "Ljubljenčki", ["Trixie", "Catsan"], 9.99, "kos"],
  ["Lesni pesek za mačke", "Ljubljenčki", ["Cat's Best", "Biokat's"], 8.99, "kos"],
  ["Pasje palčke", "Ljubljenčki", ["Vitakraft", "Pedigree Rodeo", "Trixie"], 2.49, "kos"],
  ["Kosti za žvečenje", "Ljubljenčki", ["Pedigree", "Trixie", "Vitakraft"], 3.99, "kos"],
  ["Ampule proti bolham in klopom", "Ljubljenčki", ["Frontline", "Advantix", "Beaphar"], 24.99, "kos"],
  ["Ovratnica proti klopom", "Ljubljenčki", ["Seresto", "Foresto", "Beaphar"], 34.99, "kos"],
  ["Tablete proti glistam", "Ljubljenčki", ["Drontal", "Milbemax"], 9.99, "kos"],
  ["Šampon za pse", "Ljubljenčki", ["Trixie", "Beaphar"], 6.99, "kos"],
  ["Krtača za dlako", "Ljubljenčki", ["Furminator", "Trixie"], 12.99, "kos"],
  ["Igrača za psa", "Ljubljenčki", ["Kong", "Trixie"], 7.99, "kos"],
  ["Igrača za mačko", "Ljubljenčki", ["Trixie", "Kong"], 3.99, "kos"],
  ["Praskalnik za mačke", "Ljubljenčki", ["Trixie"], 24.99, "kos"],
  ["Povodec", "Ljubljenčki", ["Flexi", "Trixie"], 14.99, "kos"],
  ["Ovratnica za psa", "Ljubljenčki", ["Trixie", "Julius-K9"], 9.99, "kos"],
  ["Oprsnica za psa", "Ljubljenčki", ["Julius-K9", "Trixie"], 24.99, "kos"],
  ["Skleda za hrano", "Ljubljenčki", ["Trixie"], 5.99, "kos"],
  ["Pasja postelja", "Ljubljenčki", ["Trixie"], 29.99, "kos"],
  ["Transporter", "Ljubljenčki", ["Trixie", "Ferplast"], 24.99, "kos"],
  ["Hrana za zajce", "Ljubljenčki", ["Versele-Laga", "Vitakraft"], 3.99, "1 kg"],
  ["Seno za glodavce", "Ljubljenčki", ["Vitakraft", "Versele-Laga", "JR Farm"], 3.49, "1 kg"],
  ["Nastilj za glodavce", "Ljubljenčki", ["Chipsi", "Vitakraft"], 4.99, "kos"],
  ["Hrana za papige", "Ljubljenčki", ["Versele-Laga", "Vitakraft"], 5.99, "1 kg"],
  ["Hrana za želve", "Ljubljenčki", ["Tetra", "JBL"], 4.99, "kos"],
  ["Pripravek za akvarijsko vodo", "Ljubljenčki", ["Tetra", "JBL", "Sera"], 7.99, "kos"],

  // Brez glutena
  ["Mešanica za kruh brez glutena", "Brez glutena", ["Schär", "Mlinotest"], 3.99, "1 kg"],
  ["Prepečenec brez glutena", "Brez glutena", ["Schär"], 2.99, "150 g"],
  ["Rogljički brez glutena", "Brez glutena", ["Schär"], 4.49, "kos"],
  ["Riževi rezanci", "Brez glutena", ["Blue Dragon"], 2.49, "250 g"],
  ["Musli brez glutena", "Brez glutena", ["Schär", "Lidl"], 3.99, "375 g"],
  ["Pecivo brez glutena", "Brez glutena", ["Schär"], 3.49, "kos"],
]);
